package Presentacion;

import javax.swing.JFrame;
import Negocio.DTOs.UsuarioDTO;
import Negocio.GestorUsuario.IUsuario;
import Negocio.GestorUsuario.UsuarioFachada;
import javax.swing.JOptionPane;
import Presentacion.coordinadorVistas;

/**
 *
 * @author User
 */
public class frmCrearUsuario extends javax.swing.JFrame {

    //creamos esta variable para usarla como distintivo
    private int idUsuarioEdicion = -1;
    private byte[] imagenPerfil = null;

    /**
     * Creates new form frmCrearUsuario
     */
    public frmCrearUsuario() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * Para editar recibe el desde la tabla
     */
    public frmCrearUsuario(int idSeleccionado) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        // Guardamos el id que nos mandaron
        this.idUsuarioEdicion = idSeleccionado;

        // Cambiamos los textos para que la pantalla parezca de modificacion
        lblSubtituloCrear.setText("Modificar Usuario");
        btnCrearUsuario.setText("Guardar Cambios");

        // Mandamos a traer los datos para rellenar las cajitas de texto
        cargarDatosParaEditar();
    }

    private void cargarDatosParaEditar() {
        IUsuario fachada = new UsuarioFachada();
        // Reciclamos el metodo que hicimos para la otra pantalla
        UsuarioDTO usuario = fachada.consultarUsuarioPorId(this.idUsuarioEdicion);

        if (usuario != null) {
            // Le metemos los datos al textfield
            txtNombreCompleto.setText(usuario.getNombre());
            txtCorreo.setText(usuario.getEmail());
            txtContraseña.setText(usuario.getContrasena());
            txtConfirmarContraseña.setText(usuario.getContrasena());

            // Validamos el telefono por si esta nulo
            if (usuario.getTelefono() != null) {
                txtTelefono.setText(usuario.getTelefono());
            }

            // Seleccionamos el rol correcto en el combo box
            cbxRolAsignado.setSelectedItem(usuario.getRol());

            // mostrar la foto para editar
            this.imagenPerfil = usuario.getFotoPerfil();
            if (this.imagenPerfil != null) {
                mostrarFoto(this.imagenPerfil);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtituloCrear = new javax.swing.JLabel();
        lblNombreCompleto = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        lblContraseña = new javax.swing.JLabel();
        lblConfContraseña = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        cbxRolAsignado = new javax.swing.JComboBox<>();
        btnLimpiarCampos = new javax.swing.JButton();
        btnCrearUsuario = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblRol1 = new javax.swing.JLabel();
        btnFotoPerfil = new javax.swing.JButton();
        lblFotoPerfil = new javax.swing.JLabel();
        txtConfirmarContraseña = new javax.swing.JPasswordField();
        txtContraseña = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitulo.setText("Residencias ITSON – Panel de gestión de usuarios");
        lblTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        lblSubtituloCrear.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblSubtituloCrear.setText("Crear nuevo usuario");
        jPanel1.add(lblSubtituloCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));

        lblNombreCompleto.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblNombreCompleto.setText("Nombre completo:");
        jPanel1.add(lblNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, 40));

        txtNombreCompleto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, 460, 40));

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblCorreo.setText("Correo electronico:");
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, -1, 40));

        txtCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 460, 40));

        lblContraseña.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblContraseña.setText("Contraseña:");
        jPanel1.add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, 40));

        lblConfContraseña.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblConfContraseña.setText("Confirmar contraseña:");
        jPanel1.add(lblConfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, -1, 40));

        lblPerfil.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.add(lblPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 70, 70));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVertcalLetrasGrande.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 200, 390, 430));

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblTelefono.setText("Telefono:");
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, 40));

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 460, 40));

        cbxRolAsignado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbxRolAsignado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un Rol", "Administrador", "Trabajador" }));
        cbxRolAsignado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRolAsignadoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxRolAsignado, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 460, 40));

        btnLimpiarCampos.setBackground(new java.awt.Color(255, 102, 102));
        btnLimpiarCampos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpiarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCampos.setText("Limpiar campos");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 690, 200, 50));

        btnCrearUsuario.setBackground(new java.awt.Color(51, 153, 255));
        btnCrearUsuario.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrearUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearUsuario.setText("Crear usuario");
        btnCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 690, 200, 50));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 40));

        lblRol1.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblRol1.setText("Rol asignado:");
        jPanel1.add(lblRol1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, -1, 40));

        btnFotoPerfil.setBackground(new java.awt.Color(0, 102, 204));
        btnFotoPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnFotoPerfil.setText("Seleccionar foto");
        btnFotoPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 590, -1, 40));

        lblFotoPerfil.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblFotoPerfil.setText("Foto de peril:");
        jPanel1.add(lblFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 590, -1, 40));

        txtConfirmarContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 460, 40));

        txtContraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txtContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, 460, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1385, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        txtNombreCompleto.setText("");
        txtCorreo.setText("");
        txtContraseña.setText("");
        txtConfirmarContraseña.setText("");
        txtTelefono.setText("");
        cbxRolAsignado.setSelectedIndex(0);

    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUsuarioActionPerformed
        // Extraer los datos 
        String nombre = txtNombreCompleto.getText();
        String correo = txtCorreo.getText();
        String contra = txtContraseña.getText();
        String confContra = txtConfirmarContraseña.getText();
        String rol = cbxRolAsignado.getSelectedItem().toString();
        String telefono = txtTelefono.getText();

        //Validacion basica de las credenciales 
        if (!contra.equals(confContra)) {
            JOptionPane.showMessageDialog(this,
                    "Las contraseñas no coinciden, por favor, verificalas.",
                    "Aviso",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Crear el paquete de dtos
        UsuarioDTO dto = new UsuarioDTO();
        dto.setId(this.idUsuarioEdicion);
        dto.setNombre(nombre);
        dto.setEmail(correo);
        dto.setContrasena(contra);
        dto.setRol(rol);
        dto.setTelefono(telefono);
        dto.setFotoPerfil(this.imagenPerfil);

        // Llamamos a la Fachada
        IUsuario fachada = new UsuarioFachada();
        boolean exito;

        if (this.idUsuarioEdicion == -1) {
            exito = fachada.registrar(dto);
        } else {
            exito = fachada.actualizarUsuario(dto);

            //checamos la respuesta en esta parte
            if (exito) {
                String mensaje = (this.idUsuarioEdicion == -1) ? "Usuario registrado exitosamente." : "Usuario modificado exitosamente.";
                JOptionPane.showMessageDialog(this, mensaje, "Exito", JOptionPane.INFORMATION_MESSAGE);

                if (this.idUsuarioEdicion == -1) {
                    btnLimpiarCamposActionPerformed(evt);
                    coordinadorVistas.mostrarAdminInicio(this);
                } else {
                    coordinadorVistas.mostrarConsultarUsuarios(this);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        "No se pudo guardar. Verifica que los campos obligatorios estén llenos.",
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_btnCrearUsuarioActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        coordinadorVistas.mostrarAdminInicio(this);
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void cbxRolAsignadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRolAsignadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxRolAsignadoActionPerformed

    private void btnFotoPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoPerfilActionPerformed
        javax.swing.JFileChooser selector = new javax.swing.JFileChooser();
        selector.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Imágenes", "jpg", "png", "jpeg"));

        int resultado = selector.showOpenDialog(this);

        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = selector.getSelectedFile();
            this.imagenPerfil = leerBytesImagen(archivo);
            mostrarFoto(this.imagenPerfil);
        }
    }//GEN-LAST:event_btnFotoPerfilActionPerformed

    //Metodos para la foto de perfil
    // Metodo para convertir el archivo seleccionado a bytes
    private byte[] leerBytesImagen(java.io.File archivo) {
        try {
            return java.nio.file.Files.readAllBytes(archivo.toPath());
        } catch (java.io.IOException e) {
            System.err.println("Error al leer imagen: " + e.getMessage());
            return null;
        }
    }

    // Metodo para mostrar la foto
    private void mostrarFoto(byte[] bytes) {
        if (bytes != null) {
            java.awt.Image img = new javax.swing.ImageIcon(bytes).getImage();
            java.awt.Image nuevaImg = img.getScaledInstance(lblPerfil.getWidth(), lblPerfil.getHeight(), java.awt.Image.SCALE_SMOOTH);
            lblPerfil.setIcon(new javax.swing.ImageIcon(nuevaImg));
        } else {
            lblPerfil.setIcon(null);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCrearUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCrearUsuario;
    private javax.swing.JButton btnFotoPerfil;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JComboBox<String> cbxRolAsignado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfContraseña;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFotoPerfil;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblPerfil;
    private javax.swing.JLabel lblRol1;
    private javax.swing.JLabel lblSubtituloCrear;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField txtConfirmarContraseña;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
