/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JFrame;

/**
 *
 * @author Tesis
 */
public class frmCrearActaAdministrativa extends javax.swing.JFrame {

    private String idResidenteActual;

    /**
     * Creates new form frmCrearActaAdministrativa
     */
    public frmCrearActaAdministrativa(String idResidente) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        this.idResidenteActual = idResidente;
        cargarDatosAutomatizados();
    }

    /**
     * Trae los datos de la base de datos y pone la fecha del sistema.
     */
    private void cargarDatosAutomatizados() {
        java.time.LocalDate fechaActual = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter formato = java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy");
        txtFechaActa.setText(fechaActual.format(formato));
        txtFechaActa.setEditable(false); // Se bloquea para evitar modificaciones por error

        Negocio.GestorResidente.IResidente fachada = new Negocio.GestorResidente.ResidenteFachada();
        Negocio.DTOs.ResidenteDTO residente = fachada.consultarResidentePorId(this.idResidenteActual);

        if (residente != null) {
            txtIdEstudiante.setText(residente.getIdAcademico());
            txtIdEstudiante.setEditable(false);

            txtNombreAlumno.setText(residente.getNombreCompleto());
            txtNombreAlumno.setEditable(false);

            String carrera = residente.getCarrera() != null ? residente.getCarrera() : "No registrada";
            txtCarreraAlumno.setText(carrera);
            txtCarreraAlumno.setEditable(false);
            txtCarreraAlumno.setOpaque(false);
            txtCarreraAlumno.setBorder(javax.swing.BorderFactory.createEmptyBorder());

            String semestre = residente.getSemestre();
            if (semestre != null) {
                semestre = semestre.toLowerCase();
                if (semestre.contains("agosto") || semestre.contains("diciembre") || semestre.contains("agosto-diciembre")) {
                    chkSemestreAgostoDic.setSelected(true);
                    chkSemestreEneroMayo.setSelected(false);
                } else if (semestre.contains("enero") || semestre.contains("mayo") || semestre.contains("enero-mayo")) {
                    chkSemestreEneroMayo.setSelected(true);
                    chkSemestreAgostoDic.setSelected(false);
                }
            }

            chkSemestreAgostoDic.setEnabled(false);
            chkSemestreEneroMayo.setEnabled(false);

        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Hubo un problema al cargar la informacion del residente.",
                    "Error de carga", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtituloCrear = new javax.swing.JLabel();
        lblNombreAlumno = new javax.swing.JLabel();
        txtNombreAlumno = new javax.swing.JTextField();
        lblCarreraAlumno = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        lblFechaActa = new javax.swing.JLabel();
        txtFechaActa = new javax.swing.JTextField();
        lblInstituto = new javax.swing.JLabel();
        lblPagina = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCp = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        chkSemestreAgostoDic = new javax.swing.JCheckBox();
        chkSemestreEneroMayo = new javax.swing.JCheckBox();
        lblSemestreActa = new javax.swing.JLabel();
        lblIdEstudiante = new javax.swing.JLabel();
        txtIdEstudiante = new javax.swing.JTextField();
        lblLineamiento = new javax.swing.JLabel();
        cmbxLineamiento = new javax.swing.JComboBox<>();
        lblDescripcionActa = new javax.swing.JLabel();
        txaDescripcionActa = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        btnAtras = new javax.swing.JButton();
        btnLimpiarCampos = new javax.swing.JButton();
        btnImprimirActa = new javax.swing.JButton();
        txtCarreraAlumno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitulo.setText("Residencias ITSON – Panel de gestión de actas");
        lblTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        lblSubtituloCrear.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblSubtituloCrear.setText("Crear nueva acta");
        jPanel1.add(lblSubtituloCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));

        lblNombreAlumno.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblNombreAlumno.setText("Nombre completo:");
        jPanel1.add(lblNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, 32));

        txtNombreAlumno.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNombreAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAlumnoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 650, 32));

        lblCarreraAlumno.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblCarreraAlumno.setText("Carrera:");
        jPanel1.add(lblCarreraAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, -1, 32));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVerticalLetras.png"))); // NOI18N
        jPanel1.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, 310, 300));

        lblFechaActa.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblFechaActa.setText("Fecha:");
        jPanel1.add(lblFechaActa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, 36));

        txtFechaActa.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txtFechaActa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 260, 32));

        lblInstituto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblInstituto.setText("Instituto Tecnológico de Sonora");
        jPanel1.add(lblInstituto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        lblPagina.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblPagina.setText("Página web: www.itson.mx");
        jPanel1.add(lblPagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, -1, -1));

        lblDireccion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDireccion.setText("Dirección: 5 de Febrero No. 818 Sur");
        jPanel1.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTelefono.setText("Teléfono: (644) 410-90-00, ext. 3335");
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, -1, -1));

        lblCp.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblCp.setText("C.P. 85000 Ciudad Obregón, Sonora, México");
        jPanel1.add(lblCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, -1, 32));

        chkSemestreAgostoDic.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        chkSemestreAgostoDic.setText("Agosto - Diciembre");
        chkSemestreAgostoDic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSemestreAgostoDicActionPerformed(evt);
            }
        });
        jPanel1.add(chkSemestreAgostoDic, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 460, -1, 32));

        chkSemestreEneroMayo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        chkSemestreEneroMayo.setText("Enero - Mayo");
        chkSemestreEneroMayo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSemestreEneroMayoActionPerformed(evt);
            }
        });
        jPanel1.add(chkSemestreEneroMayo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, -1, 32));

        lblSemestreActa.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblSemestreActa.setText("Semestre de residencia:");
        jPanel1.add(lblSemestreActa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, -1, 32));

        lblIdEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblIdEstudiante.setText("Id de estudiante:");
        jPanel1.add(lblIdEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 510, 200, 32));

        txtIdEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtIdEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEstudianteActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, 240, 32));

        lblLineamiento.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblLineamiento.setText("Lineamiento incumplido:");
        jPanel1.add(lblLineamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, -1, 32));

        cmbxLineamiento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbxLineamiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cmbxLineamiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 230, 32));

        lblDescripcionActa.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lblDescripcionActa.setText("Descripción:");
        jPanel1.add(lblDescripcionActa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, -1, 32));

        txtDescripcion.setColumns(20);
        txtDescripcion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtDescripcion.setRows(5);
        txaDescripcionActa.setViewportView(txtDescripcion);

        jPanel1.add(txaDescripcionActa, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 610, 690, 120));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 40));

        btnLimpiarCampos.setBackground(new java.awt.Color(255, 102, 102));
        btnLimpiarCampos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLimpiarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarCampos.setText("Limpiar campos");
        btnLimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarCamposActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarCampos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 690, 170, 40));

        btnImprimirActa.setBackground(new java.awt.Color(51, 153, 255));
        btnImprimirActa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnImprimirActa.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimirActa.setText("Imprimir");
        btnImprimirActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActaActionPerformed(evt);
            }
        });
        jPanel1.add(btnImprimirActa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 690, 150, 40));
        jPanel1.add(txtCarreraAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 512, 170, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 839, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAlumnoActionPerformed

    private void chkSemestreAgostoDicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSemestreAgostoDicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSemestreAgostoDicActionPerformed

    private void chkSemestreEneroMayoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSemestreEneroMayoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSemestreEneroMayoActionPerformed

    private void txtIdEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEstudianteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEstudianteActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        frmAdminInicio volver = new frmAdminInicio();
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnLimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarCamposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarCamposActionPerformed

    private void btnImprimirActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnImprimirActaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnImprimirActa;
    private javax.swing.JButton btnLimpiarCampos;
    private javax.swing.JCheckBox chkSemestreAgostoDic;
    private javax.swing.JCheckBox chkSemestreEneroMayo;
    private javax.swing.JComboBox<String> cmbxLineamiento;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCarreraAlumno;
    private javax.swing.JLabel lblCp;
    private javax.swing.JLabel lblDescripcionActa;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFechaActa;
    private javax.swing.JLabel lblIdEstudiante;
    private javax.swing.JLabel lblInstituto;
    private javax.swing.JLabel lblLineamiento;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreAlumno;
    private javax.swing.JLabel lblPagina;
    private javax.swing.JLabel lblSemestreActa;
    private javax.swing.JLabel lblSubtituloCrear;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane txaDescripcionActa;
    private javax.swing.JTextField txtCarreraAlumno;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtFechaActa;
    private javax.swing.JTextField txtIdEstudiante;
    private javax.swing.JTextField txtNombreAlumno;
    // End of variables declaration//GEN-END:variables
}
