/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cesar
 */
public class frmConsultarResidente extends javax.swing.JFrame {

    private DefaultTableModel modeloResidentes;

    /**
     * Creates new form frmConsultarResidente
     */
    public frmConsultarResidente() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        configurarYcargarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloGestionResi = new javax.swing.JLabel();
        lblSubtituloSoliIngre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloGestionResi.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTituloGestionResi.setText("Residencias ITSON – Panel de Gestión de residentes");
        jPanel1.add(lblTituloGestionResi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        lblSubtituloSoliIngre.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblSubtituloSoliIngre.setText("Consultar residente");
        jPanel1.add(lblSubtituloSoliIngre, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 630, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        tblActas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tblActas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 840, 440));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVertcalLetrasGrande.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 210, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmAdminInicio adm = new frmAdminInicio();
        adm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Configura el modelo de las columnas y carga datos de ejemplo.
     */
    public void configurarYcargarTabla() {
        // 1. Títulos de columnas basados en la imagen (Solo 4 columnas)
        String[] titulos = {"ID", "Nombre residente", "Nacionalidad", ""};

        modeloResidentes = new javax.swing.table.DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Solo la columna 3 (donde va el botón SELECT) es editable para recibir clics
                return column == 3;
            }
        };

        tblActas.setModel(modeloResidentes);
        tblActas.setRowHeight(55); // Un poco más alto para que quepa bien el botón azul
        tblActas.setBackground(java.awt.Color.WHITE);

        // 2. Configurar Render y Editor solo para la Columna 3 (Índice 3)
        // Usamos la ruta forzada para asegurar que salga el botón "SELECT"
        String rutaBoton = "/Imagenes/cursor.png"; // Asegúrate que tu imagen se llame así

        tblActas.getColumnModel().getColumn(3).setCellRenderer(
                new Utilidades.RenderImagen(rutaBoton)
        );

        tblActas.getColumnModel().getColumn(3).setCellEditor(
                new Utilidades.EditorImagen(new javax.swing.JCheckBox(), tblActas, rutaBoton)
        );

        // 3. Ajuste de anchos para que se parezca a la imagen
        tblActas.getColumnModel().getColumn(0).setPreferredWidth(100); // ID
        tblActas.getColumnModel().getColumn(1).setPreferredWidth(250); // Nombre (más ancho)
        tblActas.getColumnModel().getColumn(2).setPreferredWidth(100); // Nacionalidad
        tblActas.getColumnModel().getColumn(3).setPreferredWidth(100); // Botón

        // 4. Cargar datos de prueba
        llenarTablaEjemplo();
    }

    /**
     * Simula los datos mostrados en la imagen.
     */
    private void llenarTablaEjemplo() {
        // Datos extraídos visualmente de tu imagen
        Object[] fila1 = {"00000226088", "panfilo filomeno", "Méxicana", "SELECT"};
        Object[] fila2 = {"00000226089", "Cesar Adrian Duran Avalos", "Méxicana", "SELECT"};
        Object[] fila3 = {"00000226090", "Georgina Aviles", "Colombiano", "SELECT"};
        Object[] fila4 = {"00000226091", "Jose Duran", "Colombiano", "SELECT"};

        modeloResidentes.addRow(fila1);
        modeloResidentes.addRow(fila2);
        modeloResidentes.addRow(fila3);
        modeloResidentes.addRow(fila4);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConsultarResidente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConsultarResidente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConsultarResidente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConsultarResidente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConsultarResidente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblSubtituloSoliIngre;
    private javax.swing.JLabel lblTituloGestionResi;
    private javax.swing.JTable tblActas;
    // End of variables declaration//GEN-END:variables
}
