package Presentacion;

import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tesis
 */
public class frmConsultarResidente extends javax.swing.JFrame {

    private DefaultTableModel modeloResidentes;
    private javax.swing.table.TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form frmConsultarResidente
     */
    public frmConsultarResidente() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        configurarYcargarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloGestionResi = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        lblBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblActas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloGestionResi.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTituloGestionResi.setText("Residencias ITSON – Panel de Gestión de residentes");
        jPanel1.add(lblTituloGestionResi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblSubtitulo.setText("Consultar residente");
        jPanel1.add(lblSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));
        jPanel1.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 770, 35));

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        jPanel1.add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 40, -1));

        tblActas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        jScrollPane1.setViewportView(tblActas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 1040, 440));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoVerticalLetras.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 280, 320, 340));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        coordinadorVistas.regresarMenuPrincipal(this);

    }//GEN-LAST:event_btnVolverActionPerformed

    public void configurarYcargarTabla() {
        // Titulos de columnas
        String[] titulos = {"ID", "Nombre residente", "Nacionalidad", ""};

        modeloResidentes = new javax.swing.table.DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 3;
            }
        };

        tblActas.setModel(modeloResidentes);

        // conecta e filtro de buscar a la tabla
        sorter = new javax.swing.table.TableRowSorter<>(modeloResidentes);
        tblActas.setRowSorter(sorter);

        tblActas.setRowHeight(55);
        tblActas.setBackground(java.awt.Color.WHITE);

        String rutaBoton = "/Imagenes/cursor.png";

        tblActas.getColumnModel().getColumn(3).setCellRenderer(
                new Utilidades.RenderImagen(rutaBoton)
        );

        tblActas.getColumnModel().getColumn(3).setCellEditor(
                new Utilidades.EditorImagen(new javax.swing.JCheckBox(), tblActas, rutaBoton)
        );

        // Ajuste de ancho de las columnas
        tblActas.getColumnModel().getColumn(0).setPreferredWidth(100); // ID
        tblActas.getColumnModel().getColumn(1).setPreferredWidth(250); // Nombre
        tblActas.getColumnModel().getColumn(2).setPreferredWidth(100); // Nacionalidad
        tblActas.getColumnModel().getColumn(3).setPreferredWidth(100); // Boton

        // cargar datos
        cargarResidentes();

        // va filtrando depende a lo que escriban
        txtBuscar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filtrarTabla();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filtrarTabla();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filtrarTabla();
            }

            private void filtrarTabla() {
                String texto = txtBuscar.getText().trim();
                if (texto.isEmpty()) {
                    sorter.setRowFilter(null);
                } else {
                    //permite buscar sin importar mayúsculas o minúsculas
                    sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
                }
            }
        });

        tblActas.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int filaVisual = tblActas.rowAtPoint(evt.getPoint());
                int columna = tblActas.columnAtPoint(evt.getPoint());

                if (filaVisual >= 0 && columna == 3) {

                    int filaReal = tblActas.convertRowIndexToModel(filaVisual);

                    // extrae el id del residente de la fila real
                    String idSeleccionado = tblActas.getModel().getValueAt(filaReal, 0).toString();

                    coordinadorVistas.mostrarPerfilResidente(frmConsultarResidente.this, idSeleccionado);
                }
            }
        });
    }

    /**
     * Consulta la Base de Datos y llena la tabla con los residentes reales.
     */
    private void cargarResidentes() {
        // limpia la tabla por si tuviera datos viejos
        modeloResidentes.setRowCount(0);

        // llama a fachada
        Negocio.GestorResidente.IResidente fachada = new Negocio.GestorResidente.ResidenteFachada();
        java.util.List<Negocio.DTOs.ResidenteDTO> listaResidentes = fachada.consultarResidentes();

        // muestar los recidentes
        if (listaResidentes != null) {
            for (Negocio.DTOs.ResidenteDTO res : listaResidentes) {

                String id = res.getIdAcademico();
                String nombre = res.getNombreCompleto();
                String nacionalidad = res.getLugarResidencia() != null ? res.getLugarResidencia() : "N/A";

                Object[] fila = {
                    id,
                    nombre,
                    nacionalidad,
                    ""
                };

                modeloResidentes.addRow(fila);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConsultarResidente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConsultarResidente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConsultarResidente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConsultarResidente.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmConsultarResidente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTituloGestionResi;
    private javax.swing.JTable tblActas;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
