package Presentacion;

import Negocio.DTOs.DocumentoDTO;
import Negocio.DTOs.ResidenteDTO;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valeria
 */
public class frmHistorialResidente extends javax.swing.JFrame {

    private DefaultTableModel modeloHistorialRecidente;
    private ResidenteDTO residenteActual;
    private javax.swing.table.TableRowSorter<DefaultTableModel> sorter;

    /**
     * Creates new form frmHistorialResidente
     */
    public frmHistorialResidente() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        configurarYcargarTabla();
    }

    /**
     * Recibe al residente para mostrar su información y buscar sus documentos
     */
    public frmHistorialResidente(ResidenteDTO residente) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        this.residenteActual = residente;

        if (this.residenteActual != null) {
            lblNombreResidente.setText(this.residenteActual.getNombreCompleto());
            lblIdResidente.setText(this.residenteActual.getIdAcademico());
        }

        configurarYcargarTabla();
        cargarFotoFormal();
        
        
        // buscador dinamico, detecta cambios en el txt en tiempo real
        txtBuscar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filtrarTabla();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filtrarTabla();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filtrarTabla();
            }
            
            private void filtrarTabla() {
                String texto = txtBuscar.getText().trim();
                if (texto.isEmpty()) {
                    sorter.setRowFilter(null); 
                } else {
                    sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHistorialResidente = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblSubtitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHistorial = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblFotoPerfil = new javax.swing.JLabel();
        lblNombreResidente = new javax.swing.JLabel();
        lblIdResidente = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlHistorialResidente.setBackground(new java.awt.Color(255, 255, 255));
        pnlHistorialResidente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblTitulo.setText("Residencias ITSON – Panel de gestión de residentes");
        lblTitulo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlHistorialResidente.add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, -1, -1));

        lblSubtitulo.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblSubtitulo.setText("Historial de residente");
        pnlHistorialResidente.add(lblSubtitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, -1, -1));

        tblHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHistorial);

        pnlHistorialResidente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 1080, 370));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        pnlHistorialResidente.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 40));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoLetrasChico.png"))); // NOI18N
        pnlHistorialResidente.add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 100, 150, 170));

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombre.setText("Nombre:");
        pnlHistorialResidente.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, -1, 25));

        lblId.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblId.setText("ID:");
        pnlHistorialResidente.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, 25));

        lblFotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/perfilRecidente.png"))); // NOI18N
        pnlHistorialResidente.add(lblFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 130, -1));

        lblNombreResidente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNombreResidente.setText("nombre");
        pnlHistorialResidente.add(lblNombreResidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, 25));

        lblIdResidente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIdResidente.setText("id");
        pnlHistorialResidente.add(lblIdResidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, -1, 25));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar.png"))); // NOI18N
        pnlHistorialResidente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));
        pnlHistorialResidente.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 770, 35));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHistorialResidente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlHistorialResidente, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
       if (this.residenteActual != null) {
            coordinadorVistas.mostrarPerfilResidente(this, this.residenteActual.getIdAcademico()); 
        } else {
            coordinadorVistas.regresarMenuPrincipal(this);
        }
    }//GEN-LAST:event_btnAtrasActionPerformed

    public void configurarYcargarTabla() {
        String[] titulos = {"Documento", "Fecha", "Descargar", "Visualizar"};

        modeloHistorialRecidente = new javax.swing.table.DefaultTableModel(null, titulos) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tblHistorial.setModel(modeloHistorialRecidente);
        
        //  para filtrar la busqueda
        sorter = new javax.swing.table.TableRowSorter<>(modeloHistorialRecidente);
        tblHistorial.setRowSorter(sorter);

        tblHistorial.setRowHeight(55);
        tblHistorial.setBackground(java.awt.Color.WHITE);

        String rutaBotonDesc = "/Imagenes/descargar.png";
        String rutaBotonVisu = "/Imagenes/vision.png";

        tblHistorial.getColumnModel().getColumn(2).setCellRenderer(
                new Utilidades.RenderImagen(rutaBotonDesc)
        );
        tblHistorial.getColumnModel().getColumn(3).setCellRenderer(
                new Utilidades.RenderImagen(rutaBotonVisu)
        );

        tblHistorial.getColumnModel().getColumn(0).setPreferredWidth(150);
        tblHistorial.getColumnModel().getColumn(1).setPreferredWidth(100);
        tblHistorial.getColumnModel().getColumn(2).setPreferredWidth(80);
        tblHistorial.getColumnModel().getColumn(3).setPreferredWidth(80);

        // carga los docuemntos desde la base de datos
        llenarTablaDocumentos();

        // ba buscando al ir escribiendo
        txtBuscar.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                filtrarTabla();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                filtrarTabla();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                filtrarTabla();
            }
            
            private void filtrarTabla() {
                String texto = txtBuscar.getText().trim();
                if (texto.isEmpty()) {
                    sorter.setRowFilter(null); 
                } else {
                    sorter.setRowFilter(javax.swing.RowFilter.regexFilter("(?i)" + texto));
                }
            }
        });

        tblHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int filaVisual = tblHistorial.rowAtPoint(evt.getPoint());
                int columna = tblHistorial.columnAtPoint(evt.getPoint());

                if (filaVisual >= 0 && (columna == 2 || columna == 3)) {

                    int filaReal = tblHistorial.convertRowIndexToModel(filaVisual);
                    String tipoDocumento = tblHistorial.getModel().getValueAt(filaReal, 0).toString();

                    if (columna == 2) {
                        descargarDocumento(tipoDocumento);
                    } else if (columna == 3) {
                        visualizarDocumento(tipoDocumento);
                    }
                }
            }
        });
    }

    /**
     * Busca los documentos del residente en la BD y los pone en la tabla
     */
    private void llenarTablaDocumentos() {
        modeloHistorialRecidente.setRowCount(0);

        if (this.residenteActual == null || this.residenteActual.getIdAcademico() == null) {
            return;
        }

        Negocio.GestorResidente.IResidente fachada = new Negocio.GestorResidente.ResidenteFachada();
        java.util.List<DocumentoDTO> listaDocs = fachada.consultarDocumentos(this.residenteActual.getIdAcademico());

        if (listaDocs != null) {
            for (DocumentoDTO doc : listaDocs) {
                String fecha = doc.getFechaSubida() != null ? doc.getFechaSubida().toString() : "Reciente";

                Object[] fila = {
                    doc.getTipoDocumento(),
                    fecha,
                    "",
                    ""
                };
                modeloHistorialRecidente.addRow(fila);
            }
        }
    }
    
    /**
     * Consulta la foto del residente en la BD y para mostrarla en el perfil
     */
    private void cargarFotoFormal() {
        if (this.residenteActual == null || this.residenteActual.getIdAcademico() == null || this.residenteActual.getIdAcademico().trim().isEmpty()) {
            return; // Si no hay ID, no hacemos nada
        }

        try {
            Negocio.GestorResidente.IResidente fachada = new Negocio.GestorResidente.ResidenteFachada();

            Negocio.DTOs.DocumentoDTO foto = fachada.consultarDocumento(
                    this.residenteActual.getIdAcademico(),
                    "Foto formal"
            );

            if (foto == null || foto.getArchivo() == null || foto.getArchivo().length == 0) {
                return;
            }

            javax.swing.ImageIcon iconoOriginal = new javax.swing.ImageIcon(foto.getArchivo());

            java.awt.Image imagenEscalada = iconoOriginal.getImage().getScaledInstance(
                    lblFotoPerfil.getWidth(),
                    lblFotoPerfil.getHeight(),
                    java.awt.Image.SCALE_SMOOTH
            );

            lblFotoPerfil.setIcon(new javax.swing.ImageIcon(imagenEscalada));
            lblFotoPerfil.setText("");

        } catch (Exception e) {
            System.err.println("Error al cargar foto formal en historial: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * logica para descargar el docuemnto
     */
    private void descargarDocumento(String tipoDocumento) {
        Negocio.GestorResidente.IResidente fachada = new Negocio.GestorResidente.ResidenteFachada();
        DocumentoDTO doc = fachada.consultarDocumento(this.residenteActual.getIdAcademico(), tipoDocumento);

        if (doc == null || doc.getArchivo() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo recuperar el archivo de la base de datos.");
            return;
        }

        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setDialogTitle("Guardar Documento");
        chooser.setSelectedFile(new File(doc.getNombreArchivo()));

        if (chooser.showSaveDialog(this) == javax.swing.JFileChooser.APPROVE_OPTION) {
            File archivoDestino = chooser.getSelectedFile();
            try (FileOutputStream fos = new FileOutputStream(archivoDestino)) {
                fos.write(doc.getArchivo());
                javax.swing.JOptionPane.showMessageDialog(this, "Archivo guardado con éxito.");
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar el archivo: " + e.getMessage());
            }
        }
    }

    /**
     * logica para Abrir el PDF sin descargarlo
     */
    private void visualizarDocumento(String tipoDocumento) {
        Negocio.GestorResidente.IResidente fachada = new Negocio.GestorResidente.ResidenteFachada();
        DocumentoDTO doc = fachada.consultarDocumento(this.residenteActual.getIdAcademico(), tipoDocumento);

        if (doc == null || doc.getArchivo() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo recuperar el archivo de la base de datos.");
            return;
        }

        try {
            File archivoTemp = File.createTempFile("VistaPrevia_", "_" + doc.getNombreArchivo());
            archivoTemp.deleteOnExit();

            try (FileOutputStream fos = new FileOutputStream(archivoTemp)) {
                fos.write(doc.getArchivo());
            }

            if (java.awt.Desktop.isDesktopSupported()) {
                java.awt.Desktop.getDesktop().open(archivoTemp);
            }

        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al abrir el visualizador: " + e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHistorialResidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHistorialResidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHistorialResidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHistorialResidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHistorialResidente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFotoPerfil;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIdResidente;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreResidente;
    private javax.swing.JLabel lblSubtitulo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlHistorialResidente;
    private javax.swing.JTable tblHistorial;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
