package Presentacion;

import java.io.File;
import javax.swing.JFrame;

/**
 *
 * @author cesar
 */
public class frmRDP extends javax.swing.JFrame {

    pnlDatosSolicitante panelSolicitante = new pnlDatosSolicitante();
    pnlDatosTutor panelTutor = new pnlDatosTutor();
    pnlContactoEmergencia panelEmergencia = new pnlContactoEmergencia();
    pnlAspAcademicos panelPersonales = new pnlAspAcademicos();
    pnlAspPersonales panelAcademicos = new pnlAspPersonales();
    pnlDatosMedicos panelMedicos = new pnlDatosMedicos();

    /**
     * Creates new form frmCrearResidente
     */
    public frmRDP() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

//        pnlDatosSolicitante.add("Solicitante", panelSolicitante);
//        jTabbedPane9.addTab("Tutor", panelTutor);
//        jTabbedPane10.addTab("Emergencia", panelEmergencia);
//        jTabbedPane11.addTab("Personales", panelPersonales);
//        jTabbedPane12.addTab("Académicos", panelAcademicos);
//        jTabbedPane13.addTab("Médicos", panelMedicos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnVaciarCampos = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblSubTitulo = new javax.swing.JLabel();
        lblSubTitulo1 = new javax.swing.JLabel();
        tabDatosRegistroResi = new javax.swing.JTabbedPane();
        sllpDatosSolicitante = new javax.swing.JScrollPane();
        pnlDatosSolicitante1 = new Presentacion.pnlDatosSolicitante();
        scllpDatosTutor = new javax.swing.JScrollPane();
        pnlDatosTutor1 = new Presentacion.pnlDatosTutor();
        scllpDatosContactoEm = new javax.swing.JScrollPane();
        scllpAsPersonales = new javax.swing.JScrollPane();
        scllpAspAcademicos = new javax.swing.JScrollPane();
        scllpDatosMedicos = new javax.swing.JScrollPane();
        pnlFondoTabs = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));

        btnGuardar.setBackground(new java.awt.Color(51, 204, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");

        btnVaciarCampos.setBackground(new java.awt.Color(255, 51, 51));
        btnVaciarCampos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVaciarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnVaciarCampos.setText("Vaciar campos");

        btnImprimir.setBackground(new java.awt.Color(51, 153, 255));
        btnImprimir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnImprimir.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir.setText("Imprimir");

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(421, Short.MAX_VALUE)
                .addComponent(btnVaciarCampos)
                .addGap(62, 62, 62)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVaciarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlTitulo.setBackground(new java.awt.Color(255, 255, 255));

        lblSubTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblSubTitulo.setText("Residencias ITSON – Panel de Gestión de residentes");

        lblSubTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblSubTitulo1.setText("Registrar residente");

        tabDatosRegistroResi.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        tabDatosRegistroResi.setToolTipText("");

        sllpDatosSolicitante.setBackground(new java.awt.Color(255, 255, 255));
        sllpDatosSolicitante.setBorder(null);
        sllpDatosSolicitante.setHorizontalScrollBar(null);
        sllpDatosSolicitante.setViewportView(pnlDatosSolicitante1);

        tabDatosRegistroResi.addTab("Datos del solicitante", sllpDatosSolicitante);

        scllpDatosTutor.setToolTipText("");
        scllpDatosTutor.setHorizontalScrollBar(null);
        scllpDatosTutor.setViewportView(pnlDatosTutor1);

        tabDatosRegistroResi.addTab("Datos del Tutor", scllpDatosTutor);
        tabDatosRegistroResi.addTab("Contacto de emergencia", scllpDatosContactoEm);
        tabDatosRegistroResi.addTab("Aspectos personales", scllpAsPersonales);
        tabDatosRegistroResi.addTab("Aspectos académicos", scllpAspAcademicos);
        tabDatosRegistroResi.addTab("Datos médicos", scllpDatosMedicos);

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabDatosRegistroResi, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblSubTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(487, 487, 487))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(lblSubTitulo)
                .addGap(239, 239, 239))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(lblSubTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubTitulo1)
                .addGap(18, 18, 18)
                .addComponent(tabDatosRegistroResi, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlFondoTabs.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondoTabs.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlFondoTabs, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRDP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnVaciarCampos;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblSubTitulo1;
    private javax.swing.JPanel pnlBotones;
    private Presentacion.pnlDatosSolicitante pnlDatosSolicitante1;
    private Presentacion.pnlDatosTutor pnlDatosTutor1;
    private javax.swing.JPanel pnlFondoTabs;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JScrollPane scllpAsPersonales;
    private javax.swing.JScrollPane scllpAspAcademicos;
    private javax.swing.JScrollPane scllpDatosContactoEm;
    private javax.swing.JScrollPane scllpDatosMedicos;
    private javax.swing.JScrollPane scllpDatosTutor;
    private javax.swing.JScrollPane sllpDatosSolicitante;
    private javax.swing.JTabbedPane tabDatosRegistroResi;
    // End of variables declaration//GEN-END:variables
}
