/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JFrame;

/**
 *
 * @author cesar
 */
public class frmRegistrarResidente extends javax.swing.JFrame {

    /**
     * Creates new form frmRegistrarResidente
     */
    public frmRegistrarResidente() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        configurarTabla();

    }

    private void configurarTabla() {
        String[] columnas = {"Documento", "Nombre", "Estado", "Subir"};
        Object[][] datos = {
            {"INE/Identificación", "", "", "Subir"},
            {"INE Tutor", "", "", "Subir"},
            {"Acta de nacimiento", "", "", "Subir"},
            {"Comprobante domicilio", "", "", "Subir"},
            {"Comprobante pago", "", "", "Subir"},
            {"Foto formal", "", "", "Subir"},
            {"SIR Firmada", "", "", "Subir"},
            {"RDP Firmada", "", "", "Subir"}
        };

        // Creamos el modelo y hacemos que solo la columna 3 sea editable (para el clic)
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(datos, columnas) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 3; // Solo la columna "Subir" es editable
            }
        };

        tblRegistroResidente.setModel(modelo);

        // --- IMPORTANTE: CONFIGURACIÓN VISUAL ---
        // 1. Altura de fila (necesaria para que se vea bien la imagen)
        tblRegistroResidente.setRowHeight(51);

        // 2. Fondo blanco para toda la tabla (para que coincida con la imagen)
        tblRegistroResidente.setBackground(java.awt.Color.WHITE);

        // 3. Asignar el Render y Editor NUEVOS a la columna 3 (índice empieza en 0)
        // Columna 3 es la cuarta columna ("Subir")
        tblRegistroResidente.getColumnModel().getColumn(3).setCellRenderer(new Utilidades.RenderImagen());
        tblRegistroResidente.getColumnModel().getColumn(3).setCellEditor(new Utilidades.EditorImagen(new javax.swing.JCheckBox()));

        // Opcional: Ajustar ancho de la columna del botón
        tblRegistroResidente.getColumnModel().getColumn(3).setPreferredWidth(50);
    }

//    javax.swing.table.DefaultTableModel modelo =
//            new javax.swing.table.DefaultTableModel(datos, columnas) {
//                @Override
//                public boolean isCellEditable(int row, int column) {
//                    return column == 3; // solo la columna de botón
//                }
//
//                @Override
//                public Class<?> getColumnClass(int columnIndex) {
//                    if (columnIndex == 3) return javax.swing.JButton.class;
//                    return String.class;
//                }
//            };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jplFrmRegisResi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistroResidente = new javax.swing.JTable();
        btnRDP = new javax.swing.JButton();
        btnSolicitudIngreso = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jplFrmRegisResi.setBackground(new java.awt.Color(255, 255, 255));
        jplFrmRegisResi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("Gestion Residente");
        jplFrmRegisResi.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, -1, -1));

        tblRegistroResidente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegistroResidente);

        jplFrmRegisResi.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 1060, 440));

        btnRDP.setBackground(new java.awt.Color(204, 255, 255));
        btnRDP.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnRDP.setText("Registro de Datos Personales (RDP)");
        btnRDP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRDPActionPerformed(evt);
            }
        });
        jplFrmRegisResi.add(btnRDP, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 660, 380, 70));

        btnSolicitudIngreso.setBackground(new java.awt.Color(204, 255, 255));
        btnSolicitudIngreso.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        btnSolicitudIngreso.setText("Solicitud de ingreso");
        btnSolicitudIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSolicitudIngresoActionPerformed(evt);
            }
        });
        jplFrmRegisResi.add(btnSolicitudIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 660, 320, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel2.setText("Las identificaciones y comprobantes deben de ser recientes y o vigentes");
        jplFrmRegisResi.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 730, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jplFrmRegisResi.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplFrmRegisResi, javax.swing.GroupLayout.DEFAULT_SIZE, 1432, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jplFrmRegisResi, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRDPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRDPActionPerformed
        frmCrearResidente cr = new frmCrearResidente();
        cr.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnRDPActionPerformed

    private void btnSolicitudIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSolicitudIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSolicitudIngresoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmAdminInicio fradm = new frmAdminInicio();
        fradm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarResidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarResidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarResidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRegistrarResidente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRegistrarResidente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRDP;
    private javax.swing.JButton btnSolicitudIngreso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jplFrmRegisResi;
    private javax.swing.JTable tblRegistroResidente;
    // End of variables declaration//GEN-END:variables
}
