package Presentacion;

import javax.swing.JFrame;

/**
 *
 * @author cesar
 */
public class frmSolicitudIngreso extends javax.swing.JFrame {

    pnlDatosSolicitante panelSolicitante = new pnlDatosSolicitante();
    pnlDatosTutor panelTutor = new pnlDatosTutor();
    pnlContactoEmergencia panelEmergencia = new pnlContactoEmergencia();
    pnlFormaPago panelPago = new pnlFormaPago();
    pnlCompanero panelCompanero = new pnlCompanero();

    /**
     * Creates new form frmSolicitudIngreso
     */
    public frmSolicitudIngreso() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        // Agregamos tanto los reutilizados como los nuevos
        tabSolicitud.addTab("Solicitante", new javax.swing.JScrollPane(panelSolicitante));
        tabSolicitud.addTab("Tutor", new javax.swing.JScrollPane(panelTutor));
        tabSolicitud.addTab("Emergencia", new javax.swing.JScrollPane(panelEmergencia));
        
        // Estos solo aparecen aquí
        tabSolicitud.addTab("Forma de Pago", new javax.swing.JScrollPane(panelPago));
        tabSolicitud.addTab("Compañero", new javax.swing.JScrollPane(panelCompanero));
    
    }

    private void mostrarSeccion(javax.swing.JPanel panel) {
        panel.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBotones = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnVaciarCampos = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblSubTitulo = new javax.swing.JLabel();
        lblSubTitulo1 = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        pnlFondoTabs = new javax.swing.JPanel();
        tabSolicitud = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlBotones.setBackground(new java.awt.Color(255, 255, 255));

        btnGuardar.setBackground(new java.awt.Color(51, 204, 0));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");

        btnVaciarCampos.setBackground(new java.awt.Color(255, 51, 51));
        btnVaciarCampos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVaciarCampos.setForeground(new java.awt.Color(255, 255, 255));
        btnVaciarCampos.setText("Vaciar campos");

        javax.swing.GroupLayout pnlBotonesLayout = new javax.swing.GroupLayout(pnlBotones);
        pnlBotones.setLayout(pnlBotonesLayout);
        pnlBotonesLayout.setHorizontalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBotonesLayout.createSequentialGroup()
                .addContainerGap(613, Short.MAX_VALUE)
                .addComponent(btnVaciarCampos)
                .addGap(62, 62, 62)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(420, 420, 420))
        );
        pnlBotonesLayout.setVerticalGroup(
            pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVaciarCampos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBotones, java.awt.BorderLayout.PAGE_END);

        pnlTitulo.setBackground(new java.awt.Color(255, 255, 255));
        pnlTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSubTitulo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lblSubTitulo.setText("Residencias ITSON – Panel de Gestión de residentes");
        pnlTitulo.add(lblSubTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));

        lblSubTitulo1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblSubTitulo1.setText("Solicitud de ingreso");
        pnlTitulo.add(lblSubTitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 250, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/atras.png"))); // NOI18N
        btnAtras.setBorder(null);
        btnAtras.setBorderPainted(false);
        btnAtras.setContentAreaFilled(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        pnlTitulo.add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 60, 40));

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlFondoTabs.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondoTabs.setLayout(new java.awt.BorderLayout());

        tabSolicitud.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 100, 20, 100));
        tabSolicitud.setToolTipText("");
        pnlFondoTabs.add(tabSolicitud, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlFondoTabs, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        frmRegistrarResidente volver = new frmRegistrarResidente();
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSolicitudIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSolicitudIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSolicitudIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSolicitudIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSolicitudIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVaciarCampos;
    private javax.swing.JLabel lblSubTitulo;
    private javax.swing.JLabel lblSubTitulo1;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlFondoTabs;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTabbedPane tabSolicitud;
    // End of variables declaration//GEN-END:variables
}
