/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import javax.swing.JFrame;

/**
 *
 * @author cesar
 */
public class frmTrabajadorInicio extends javax.swing.JFrame {

    /**
     * Creates new form frmTrabajadorInicio
     */
    public frmTrabajadorInicio() {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitulodmin = new javax.swing.JLabel();
        lblBienvenidAdmin = new javax.swing.JLabel();
        lblNombreAdmin = new javax.swing.JLabel();
        lblLogoResiAdmin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jplGTNResidentes = new javax.swing.JPanel();
        lblGestionResidentesAdmin = new javax.swing.JLabel();
        cmbxGestionResidentes = new javax.swing.JComboBox<>();
        btnSeleccionarOpcionResidente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitulodmin.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        txtTitulodmin.setText("Residencias ITSON – Panel Trabajador ");
        jPanel1.add(txtTitulodmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 60, -1, -1));

        lblBienvenidAdmin.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblBienvenidAdmin.setText("Bienvenido");
        jPanel1.add(lblBienvenidAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, -1, -1));

        lblNombreAdmin.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblNombreAdmin.setText("¨Trabajador¨");
        jPanel1.add(lblNombreAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, -1, -1));

        lblLogoResiAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoResix.jpg"))); // NOI18N
        jPanel1.add(lblLogoResiAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proyecto recidencias.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 180, 710, 580));

        jplGTNResidentes.setBackground(new java.awt.Color(119, 180, 241));

        lblGestionResidentesAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGestionResidentesAdmin.setForeground(new java.awt.Color(255, 255, 255));
        lblGestionResidentesAdmin.setText("GESTION RESIDENTES");

        javax.swing.GroupLayout jplGTNResidentesLayout = new javax.swing.GroupLayout(jplGTNResidentes);
        jplGTNResidentes.setLayout(jplGTNResidentesLayout);
        jplGTNResidentesLayout.setHorizontalGroup(
            jplGTNResidentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplGTNResidentesLayout.createSequentialGroup()
                .addContainerGap(61, Short.MAX_VALUE)
                .addComponent(lblGestionResidentesAdmin)
                .addGap(41, 41, 41))
        );
        jplGTNResidentesLayout.setVerticalGroup(
            jplGTNResidentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGTNResidentesLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblGestionResidentesAdmin)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jPanel1.add(jplGTNResidentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 280, 110));

        cmbxGestionResidentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una opcion", "Registrar residente", "Consultar residente", "Modificar residente" }));
        cmbxGestionResidentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxGestionResidentesActionPerformed(evt);
            }
        });
        jPanel1.add(cmbxGestionResidentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 280, 80));

        btnSeleccionarOpcionResidente.setBackground(new java.awt.Color(0, 51, 204));
        btnSeleccionarOpcionResidente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeleccionarOpcionResidente.setForeground(new java.awt.Color(255, 255, 255));
        btnSeleccionarOpcionResidente.setText("Seleccionar");
        jPanel1.add(btnSeleccionarOpcionResidente, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 300, 90));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoLOgOut .png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 650, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel2.setText("Cerrar Sesion");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 670, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbxGestionResidentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxGestionResidentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbxGestionResidentesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        frmLogin frmlogs = new frmLogin();

        frmlogs.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTrabajadorInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTrabajadorInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTrabajadorInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTrabajadorInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTrabajadorInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarOpcionResidente;
    private javax.swing.JComboBox<String> cmbxGestionResidentes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jplGTNResidentes;
    private javax.swing.JLabel lblBienvenidAdmin;
    private javax.swing.JLabel lblGestionResidentesAdmin;
    private javax.swing.JLabel lblLogoResiAdmin;
    private javax.swing.JLabel lblNombreAdmin;
    private javax.swing.JLabel txtTitulodmin;
    // End of variables declaration//GEN-END:variables
}
