/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author User
 */
public class pnlAspPersonales extends javax.swing.JPanel {

    /**
     * Creates new form pnlAspPersonales
     */
    public pnlAspPersonales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblapdc1 = new javax.swing.JLabel();
        chbxSiApdc1 = new javax.swing.JCheckBox();
        chbxNoApdc1 = new javax.swing.JCheckBox();
        txtRespuestaApdc2 = new javax.swing.JTextField();
        lblapdc2 = new javax.swing.JLabel();
        lblapdc3 = new javax.swing.JLabel();
        chbxApdcTuya3 = new javax.swing.JCheckBox();
        chbxApdcTusPadres3 = new javax.swing.JCheckBox();
        chbxApdcAmbos3 = new javax.swing.JCheckBox();
        lblapdc3_3 = new javax.swing.JLabel();
        lblapdc4 = new javax.swing.JLabel();
        lblapdc4_4 = new javax.swing.JLabel();
        lblapdc5 = new javax.swing.JLabel();
        txtRespuestaApdc4 = new javax.swing.JTextField();
        chbxApdcDificilmente5 = new javax.swing.JCheckBox();
        chbxApdcRegularmente5 = new javax.swing.JCheckBox();
        chbxApdcFacilmente5 = new javax.swing.JCheckBox();
        chbxApdcPersuadir6 = new javax.swing.JCheckBox();
        chbxApdcNegociar6 = new javax.swing.JCheckBox();
        chbxApdcCeder6 = new javax.swing.JCheckBox();
        lblapdc6 = new javax.swing.JLabel();
        lblapdc7 = new javax.swing.JLabel();
        txtRespuestaApdc7 = new javax.swing.JTextField();
        lblapdc7_7 = new javax.swing.JLabel();
        lblapdc8 = new javax.swing.JLabel();
        chbxApdcExtranjero8 = new javax.swing.JCheckBox();
        chbxApdcMexicano8 = new javax.swing.JCheckBox();
        chbxApdcReingrenso8 = new javax.swing.JCheckBox();
        lblapdc9 = new javax.swing.JLabel();
        cmbxApdcHora9 = new javax.swing.JComboBox<>();
        lblapdc10 = new javax.swing.JLabel();
        lblapdc11 = new javax.swing.JLabel();
        lblapdc12 = new javax.swing.JLabel();
        lblapdc13 = new javax.swing.JLabel();
        chbxApdcAuto13 = new javax.swing.JCheckBox();
        chbxApdcCompu13 = new javax.swing.JCheckBox();
        chbxApdcSi10 = new javax.swing.JCheckBox();
        chbxApdcNo10 = new javax.swing.JCheckBox();
        chbxApdcPoco11 = new javax.swing.JCheckBox();
        chbxApdcPoco12 = new javax.swing.JCheckBox();
        chbxApdcRegular11 = new javax.swing.JCheckBox();
        chbxApdcRegulares12 = new javax.swing.JCheckBox();
        chbxApdcMuyImportante11 = new javax.swing.JCheckBox();
        chbxApdcMuyEstrictos12 = new javax.swing.JCheckBox();
        chbxApdcTV13 = new javax.swing.JCheckBox();
        chbxApdcFrigobr13 = new javax.swing.JCheckBox();
        lblapdc14 = new javax.swing.JLabel();
        chbxApdcSi14 = new javax.swing.JCheckBox();
        chbxApdcNo14 = new javax.swing.JCheckBox();
        chbxApdcAlgunasVeces14 = new javax.swing.JCheckBox();
        lblapdc15 = new javax.swing.JLabel();
        lblapdc16 = new javax.swing.JLabel();
        lblapdc17 = new javax.swing.JLabel();
        lblapdc18 = new javax.swing.JLabel();
        lblapdc17_17 = new javax.swing.JLabel();
        cmbxApdcGrupo16 = new javax.swing.JComboBox<>();
        chbxApdcSi15 = new javax.swing.JCheckBox();
        chbxApdcNo15 = new javax.swing.JCheckBox();
        txtApdcActividades17 = new javax.swing.JTextField();
        chbxApdcDeportivas18 = new javax.swing.JCheckBox();
        chbxApdcCulturales18 = new javax.swing.JCheckBox();
        chbxApdcArtisticas18 = new javax.swing.JCheckBox();
        cmbxApdcAspecto19 = new javax.swing.JComboBox<>();
        txtApdcInfoResi20 = new javax.swing.JTextField();
        lblapdc20 = new javax.swing.JLabel();
        lblapdc19 = new javax.swing.JLabel();
        lblapdc19_19 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setText("Datos de aspectos personales y de convivencia");

        lblapdc1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc1.setText("¿Has vivido fuera de tu casa anteriormente?");

        chbxSiApdc1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxSiApdc1.setText("SI");

        chbxNoApdc1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxNoApdc1.setText("NO");

        lblapdc2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc2.setText("Si tu respuesta es sí, ¿por cuánto tiempo?");

        lblapdc3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc3.setText("La decisión de vivir en Residencias ");

        chbxApdcTuya3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcTuya3.setText("Tuya");

        chbxApdcTusPadres3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcTusPadres3.setText("Tus Padres");

        chbxApdcAmbos3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcAmbos3.setText("Ambos");

        lblapdc3_3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc3_3.setText("estudiantiles es principalmente:");

        lblapdc4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc4.setText("Razones principales por las que solicitas");

        lblapdc4_4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc4_4.setText(" vivir en la residencia");

        lblapdc5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc5.setText("Adaptación a nuevas situaciones de convivencia:");

        chbxApdcDificilmente5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcDificilmente5.setText("Dificilmente");
        chbxApdcDificilmente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxApdcDificilmente5ActionPerformed(evt);
            }
        });

        chbxApdcRegularmente5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcRegularmente5.setText("Regularmente");

        chbxApdcFacilmente5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcFacilmente5.setText("Facilmente");

        chbxApdcPersuadir6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcPersuadir6.setText("Persuadir");

        chbxApdcNegociar6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcNegociar6.setText("Negociar");

        chbxApdcCeder6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcCeder6.setText("Ceder");
        chbxApdcCeder6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxApdcCeder6ActionPerformed(evt);
            }
        });

        lblapdc6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc6.setText("En la convivencia con otros, generalmente  prefieres:");

        lblapdc7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc7.setText("Cosas o situaciones que NO te gustaría ");

        lblapdc7_7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc7_7.setText("vivir durante la convivencia:");

        lblapdc8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc8.setText("Características deseadas en el compañero de habitación:");

        chbxApdcExtranjero8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcExtranjero8.setText("Extranjero");
        chbxApdcExtranjero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxApdcExtranjero8ActionPerformed(evt);
            }
        });

        chbxApdcMexicano8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcMexicano8.setText("Méxicano");

        chbxApdcReingrenso8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcReingrenso8.setText("Reingreso");

        lblapdc9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc9.setText("Hora en que acostumbras dormirte:");

        cmbxApdcHora9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cmbxApdcHora9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una hora", "9:00pm", "10:00pm", "11:00pm", "12:00am", "1:00am" }));

        lblapdc10.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc10.setText("¿Toleras cierto ruido al estudiar?");

        lblapdc11.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc11.setText("Nivel de importancia del orden:");

        lblapdc12.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc12.setText("Hábitos de higiene:");

        lblapdc13.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc13.setText("Objetos que traerás:");

        chbxApdcAuto13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcAuto13.setText("Auto");
        chbxApdcAuto13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbxApdcAuto13ActionPerformed(evt);
            }
        });

        chbxApdcCompu13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcCompu13.setText("Computadora");

        chbxApdcSi10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcSi10.setText("SI");

        chbxApdcNo10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcNo10.setText("NO");

        chbxApdcPoco11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcPoco11.setText("Poco");

        chbxApdcPoco12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcPoco12.setText("Poco");

        chbxApdcRegular11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcRegular11.setText("Regular");

        chbxApdcRegulares12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcRegulares12.setText("Regulares");

        chbxApdcMuyImportante11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcMuyImportante11.setText("Muy importante");

        chbxApdcMuyEstrictos12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcMuyEstrictos12.setText("Muy estrictos");

        chbxApdcTV13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcTV13.setText("TV");

        chbxApdcFrigobr13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcFrigobr13.setText("Frigobar");

        lblapdc14.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc14.setText("¿Participas en actividades por iniciativa propia?");

        chbxApdcSi14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcSi14.setText("SI");

        chbxApdcNo14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcNo14.setText("NO");

        chbxApdcAlgunasVeces14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcAlgunasVeces14.setText("Algunas veces");

        lblapdc15.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc15.setText("¿Has participado en algún grupo, club o equipo?");

        lblapdc16.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc16.setText("Tipo de grupo:");

        lblapdc17.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc17.setText("Actividades realizadas relacionadas con la ");

        lblapdc18.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc18.setText("Actividades que te gustaría realizar en Residencias:");

        lblapdc17_17.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc17_17.setText("pregunta anterior:");

        cmbxApdcGrupo16.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cmbxApdcGrupo16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un tipo de grupo", "Deportivo", "Cultural", "Religioso" }));

        chbxApdcSi15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcSi15.setText("SI");

        chbxApdcNo15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcNo15.setText("NO");

        chbxApdcDeportivas18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcDeportivas18.setText("Deportivas");

        chbxApdcCulturales18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcCulturales18.setText("Culturales");

        chbxApdcArtisticas18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chbxApdcArtisticas18.setText("Artisticas");

        cmbxApdcAspecto19.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        cmbxApdcAspecto19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un aspecto", "Comunicación", "Habilidades blancas", "Compañerismo", "Autoevaluación" }));

        txtApdcInfoResi20.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApdcInfoResi20FocusLost(evt);
            }
        });

        lblapdc20.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc20.setText("Otra información importante sobre ti:");

        lblapdc19.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc19.setText("Aspectos en los que te gustaría prepararte ");

        lblapdc19_19.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblapdc19_19.setText("mejor o conocer más:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(410, 410, 410)
                .addComponent(jLabel1)
                .addGap(266, 266, 266))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc1)
                        .addGap(92, 92, 92)
                        .addComponent(chbxSiApdc1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(chbxNoApdc1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc2)
                        .addGap(113, 113, 113)
                        .addComponent(txtRespuestaApdc2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblapdc3)
                            .addComponent(lblapdc3_3))
                        .addGap(170, 170, 170)
                        .addComponent(chbxApdcTuya3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(chbxApdcTusPadres3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(chbxApdcAmbos3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblapdc4)
                            .addComponent(lblapdc4_4))
                        .addGap(123, 123, 123)
                        .addComponent(txtRespuestaApdc4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc5)
                        .addGap(60, 60, 60)
                        .addComponent(chbxApdcDificilmente5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(chbxApdcRegularmente5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(chbxApdcFacilmente5, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc6)
                        .addGap(64, 64, 64)
                        .addComponent(chbxApdcCeder6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(chbxApdcNegociar6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(chbxApdcPersuadir6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblapdc7_7)
                            .addComponent(lblapdc7))
                        .addGap(126, 126, 126)
                        .addComponent(txtRespuestaApdc7, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc8)
                        .addGap(58, 58, 58)
                        .addComponent(chbxApdcExtranjero8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(chbxApdcMexicano8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(chbxApdcReingrenso8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc9)
                        .addGap(162, 162, 162)
                        .addComponent(cmbxApdcHora9, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc10)
                        .addGap(192, 192, 192)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbxApdcSi10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(chbxApdcNo10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc11)
                        .addGap(190, 190, 190)
                        .addComponent(chbxApdcPoco11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(chbxApdcRegular11, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(chbxApdcMuyImportante11, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc12)
                        .addGap(299, 299, 299)
                        .addComponent(chbxApdcPoco12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(chbxApdcRegulares12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(chbxApdcMuyEstrictos12, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc13)
                        .addGap(171, 171, 171)
                        .addComponent(chbxApdcAuto13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(chbxApdcCompu13, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(chbxApdcTV13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(chbxApdcFrigobr13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc14)
                        .addGap(62, 62, 62)
                        .addComponent(chbxApdcSi14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(chbxApdcNo14, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(chbxApdcAlgunasVeces14, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc15)
                        .addGap(116, 116, 116)
                        .addComponent(chbxApdcSi15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(chbxApdcNo15, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc16)
                        .addGap(349, 349, 349)
                        .addComponent(cmbxApdcGrupo16, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblapdc17_17)
                            .addComponent(lblapdc17))
                        .addGap(102, 102, 102)
                        .addComponent(txtApdcActividades17, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc18)
                        .addGap(70, 70, 70)
                        .addComponent(chbxApdcDeportivas18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(chbxApdcCulturales18, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(chbxApdcArtisticas18, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblapdc19)
                            .addComponent(lblapdc19_19))
                        .addGap(98, 98, 98)
                        .addComponent(cmbxApdcAspecto19, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc20)
                        .addGap(147, 147, 147)
                        .addComponent(txtApdcInfoResi20, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc1)
                    .addComponent(chbxSiApdc1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxNoApdc1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc2)
                    .addComponent(txtRespuestaApdc2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblapdc3)
                        .addGap(3, 3, 3)
                        .addComponent(lblapdc3_3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chbxApdcTuya3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbxApdcTusPadres3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chbxApdcAmbos3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblapdc4_4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtRespuestaApdc4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc5)
                    .addComponent(chbxApdcDificilmente5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcRegularmente5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcFacilmente5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc6)
                    .addComponent(chbxApdcCeder6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcNegociar6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcPersuadir6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblapdc7_7))
                    .addComponent(lblapdc7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtRespuestaApdc7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc8)
                    .addComponent(chbxApdcExtranjero8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcMexicano8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcReingrenso8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc9)
                    .addComponent(cmbxApdcHora9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc10)
                    .addComponent(chbxApdcSi10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcNo10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc11)
                    .addComponent(chbxApdcPoco11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcRegular11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcMuyImportante11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc12)
                    .addComponent(chbxApdcPoco12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcRegulares12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcMuyEstrictos12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc13)
                    .addComponent(chbxApdcAuto13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcCompu13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcTV13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcFrigobr13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc14)
                    .addComponent(chbxApdcSi14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcNo14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcAlgunasVeces14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc15)
                    .addComponent(chbxApdcSi15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcNo15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc16)
                    .addComponent(cmbxApdcGrupo16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblapdc17_17))
                    .addComponent(lblapdc17)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtApdcActividades17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc18)
                    .addComponent(chbxApdcDeportivas18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcCulturales18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chbxApdcArtisticas18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc19)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblapdc19_19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cmbxApdcAspecto19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblapdc20)
                    .addComponent(txtApdcInfoResi20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chbxApdcDificilmente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxApdcDificilmente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbxApdcDificilmente5ActionPerformed

    private void chbxApdcCeder6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxApdcCeder6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbxApdcCeder6ActionPerformed

    private void chbxApdcExtranjero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxApdcExtranjero8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbxApdcExtranjero8ActionPerformed

    private void chbxApdcAuto13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbxApdcAuto13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chbxApdcAuto13ActionPerformed

    private void txtApdcInfoResi20FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApdcInfoResi20FocusLost
//        if (!txtApdcInfoResi20.getText().trim().isEmpty()) {
//            mostrarSeccion(JpnlAspectosAcademicos);
//        }
    }//GEN-LAST:event_txtApdcInfoResi20FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chbxApdcAlgunasVeces14;
    private javax.swing.JCheckBox chbxApdcAmbos3;
    private javax.swing.JCheckBox chbxApdcArtisticas18;
    private javax.swing.JCheckBox chbxApdcAuto13;
    private javax.swing.JCheckBox chbxApdcCeder6;
    private javax.swing.JCheckBox chbxApdcCompu13;
    private javax.swing.JCheckBox chbxApdcCulturales18;
    private javax.swing.JCheckBox chbxApdcDeportivas18;
    private javax.swing.JCheckBox chbxApdcDificilmente5;
    private javax.swing.JCheckBox chbxApdcExtranjero8;
    private javax.swing.JCheckBox chbxApdcFacilmente5;
    private javax.swing.JCheckBox chbxApdcFrigobr13;
    private javax.swing.JCheckBox chbxApdcMexicano8;
    private javax.swing.JCheckBox chbxApdcMuyEstrictos12;
    private javax.swing.JCheckBox chbxApdcMuyImportante11;
    private javax.swing.JCheckBox chbxApdcNegociar6;
    private javax.swing.JCheckBox chbxApdcNo10;
    private javax.swing.JCheckBox chbxApdcNo14;
    private javax.swing.JCheckBox chbxApdcNo15;
    private javax.swing.JCheckBox chbxApdcPersuadir6;
    private javax.swing.JCheckBox chbxApdcPoco11;
    private javax.swing.JCheckBox chbxApdcPoco12;
    private javax.swing.JCheckBox chbxApdcRegular11;
    private javax.swing.JCheckBox chbxApdcRegulares12;
    private javax.swing.JCheckBox chbxApdcRegularmente5;
    private javax.swing.JCheckBox chbxApdcReingrenso8;
    private javax.swing.JCheckBox chbxApdcSi10;
    private javax.swing.JCheckBox chbxApdcSi14;
    private javax.swing.JCheckBox chbxApdcSi15;
    private javax.swing.JCheckBox chbxApdcTV13;
    private javax.swing.JCheckBox chbxApdcTusPadres3;
    private javax.swing.JCheckBox chbxApdcTuya3;
    private javax.swing.JCheckBox chbxNoApdc1;
    private javax.swing.JCheckBox chbxSiApdc1;
    private javax.swing.JComboBox<String> cmbxApdcAspecto19;
    private javax.swing.JComboBox<String> cmbxApdcGrupo16;
    private javax.swing.JComboBox<String> cmbxApdcHora9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblapdc1;
    private javax.swing.JLabel lblapdc10;
    private javax.swing.JLabel lblapdc11;
    private javax.swing.JLabel lblapdc12;
    private javax.swing.JLabel lblapdc13;
    private javax.swing.JLabel lblapdc14;
    private javax.swing.JLabel lblapdc15;
    private javax.swing.JLabel lblapdc16;
    private javax.swing.JLabel lblapdc17;
    private javax.swing.JLabel lblapdc17_17;
    private javax.swing.JLabel lblapdc18;
    private javax.swing.JLabel lblapdc19;
    private javax.swing.JLabel lblapdc19_19;
    private javax.swing.JLabel lblapdc2;
    private javax.swing.JLabel lblapdc20;
    private javax.swing.JLabel lblapdc3;
    private javax.swing.JLabel lblapdc3_3;
    private javax.swing.JLabel lblapdc4;
    private javax.swing.JLabel lblapdc4_4;
    private javax.swing.JLabel lblapdc5;
    private javax.swing.JLabel lblapdc6;
    private javax.swing.JLabel lblapdc7;
    private javax.swing.JLabel lblapdc7_7;
    private javax.swing.JLabel lblapdc8;
    private javax.swing.JLabel lblapdc9;
    private javax.swing.JTextField txtApdcActividades17;
    private javax.swing.JTextField txtApdcInfoResi20;
    private javax.swing.JTextField txtRespuestaApdc2;
    private javax.swing.JTextField txtRespuestaApdc4;
    private javax.swing.JTextField txtRespuestaApdc7;
    // End of variables declaration//GEN-END:variables
}
