package Presentacion;

import Negocio.DTOs.ResidenteDTO;

/**
 *
 * @author Valeria
 */
public class pnlAspAcademicos extends javax.swing.JPanel {

    /**
     * Creates new form pnlAspAcademicos
     */
    public pnlAspAcademicos() {
        initComponents();
        agruparCasillas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloAcademicos = new javax.swing.JLabel();
        lblBuscarAyuda = new javax.swing.JLabel();
        lblMejorasAcademicas = new javax.swing.JLabel();
        lblMejorasAcademicas2 = new javax.swing.JLabel();
        lblEfectividadTiempo = new javax.swing.JLabel();
        lblEfectividadEstudio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMejorasAcademicas = new javax.swing.JTextArea();
        chkAyudaNunca = new javax.swing.JCheckBox();
        chkTiempoMuyEfectivo = new javax.swing.JCheckBox();
        chkAyudaAVeces = new javax.swing.JCheckBox();
        chkAyudaSiempre = new javax.swing.JCheckBox();
        chkTiempoPoco = new javax.swing.JCheckBox();
        chkTiempoRegular = new javax.swing.JCheckBox();
        chkEstudioPoco = new javax.swing.JCheckBox();
        chkEstudioRegular = new javax.swing.JCheckBox();
        chkEstudioMuyEfectivo = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloAcademicos.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloAcademicos.setText("Aspectos académicos");

        lblBuscarAyuda.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblBuscarAyuda.setText("¿Sueles buscar ayuda académica cuando la necesitas?");

        lblMejorasAcademicas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblMejorasAcademicas.setText("Aspectos académicos en los que te gustaría prepararte mejor");

        lblMejorasAcademicas2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblMejorasAcademicas2.setText("(administración del tiempo, orientación vocacional, técnicas de estudio, etc.).");

        lblEfectividadTiempo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEfectividadTiempo.setText("Efectividad en la administración del tiempo:");

        lblEfectividadEstudio.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEfectividadEstudio.setText("Efectividad de tu método de estudio:");

        txaMejorasAcademicas.setColumns(20);
        txaMejorasAcademicas.setLineWrap(true);
        txaMejorasAcademicas.setRows(5);
        txaMejorasAcademicas.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txaMejorasAcademicas);

        chkAyudaNunca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAyudaNunca.setText("Casi nunca");
        chkAyudaNunca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAyudaNuncaActionPerformed(evt);
            }
        });

        chkTiempoMuyEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkTiempoMuyEfectivo.setText("Muy efectivo");
        chkTiempoMuyEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTiempoMuyEfectivoActionPerformed(evt);
            }
        });

        chkAyudaAVeces.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAyudaAVeces.setText("A veces");
        chkAyudaAVeces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAyudaAVecesActionPerformed(evt);
            }
        });

        chkAyudaSiempre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAyudaSiempre.setText("Casi siempre");
        chkAyudaSiempre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAyudaSiempreActionPerformed(evt);
            }
        });

        chkTiempoPoco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkTiempoPoco.setText("Poco efectivo");
        chkTiempoPoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTiempoPocoActionPerformed(evt);
            }
        });

        chkTiempoRegular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkTiempoRegular.setText("Regular");
        chkTiempoRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTiempoRegularActionPerformed(evt);
            }
        });

        chkEstudioPoco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkEstudioPoco.setText("Poco efectivo");
        chkEstudioPoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstudioPocoActionPerformed(evt);
            }
        });

        chkEstudioRegular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkEstudioRegular.setText("Regular");
        chkEstudioRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstudioRegularActionPerformed(evt);
            }
        });

        chkEstudioMuyEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkEstudioMuyEfectivo.setText("Muy efectivo");
        chkEstudioMuyEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstudioMuyEfectivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblTituloAcademicos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblBuscarAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(chkAyudaSiempre)
                        .addGap(43, 43, 43)
                        .addComponent(chkAyudaAVeces)
                        .addGap(55, 55, 55)
                        .addComponent(chkAyudaNunca))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblEfectividadEstudio)
                        .addGap(213, 213, 213)
                        .addComponent(chkEstudioPoco)
                        .addGap(38, 38, 38)
                        .addComponent(chkEstudioRegular)
                        .addGap(54, 54, 54)
                        .addComponent(chkEstudioMuyEfectivo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblEfectividadTiempo)
                        .addGap(153, 153, 153)
                        .addComponent(chkTiempoPoco)
                        .addGap(38, 38, 38)
                        .addComponent(chkTiempoRegular)
                        .addGap(54, 54, 54)
                        .addComponent(chkTiempoMuyEfectivo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMejorasAcademicas)
                            .addComponent(lblMejorasAcademicas2))
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloAcademicos)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBuscarAyuda)
                    .addComponent(chkAyudaSiempre)
                    .addComponent(chkAyudaAVeces)
                    .addComponent(chkAyudaNunca))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEfectividadEstudio)
                    .addComponent(chkEstudioPoco)
                    .addComponent(chkEstudioRegular)
                    .addComponent(chkEstudioMuyEfectivo))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEfectividadTiempo)
                    .addComponent(chkTiempoPoco)
                    .addComponent(chkTiempoRegular)
                    .addComponent(chkTiempoMuyEfectivo))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblMejorasAcademicas)
                        .addGap(3, 3, 3)
                        .addComponent(lblMejorasAcademicas2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkAyudaNuncaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAyudaNuncaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAyudaNuncaActionPerformed

    private void chkTiempoMuyEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTiempoMuyEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTiempoMuyEfectivoActionPerformed

    private void chkAyudaAVecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAyudaAVecesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAyudaAVecesActionPerformed

    private void chkAyudaSiempreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAyudaSiempreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAyudaSiempreActionPerformed

    private void chkTiempoPocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTiempoPocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTiempoPocoActionPerformed

    private void chkTiempoRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTiempoRegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTiempoRegularActionPerformed

    private void chkEstudioPocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstudioPocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstudioPocoActionPerformed

    private void chkEstudioRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstudioRegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstudioRegularActionPerformed

    private void chkEstudioMuyEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstudioMuyEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstudioMuyEfectivoActionPerformed

    /**
     * metodo para guardar los datos en el DTO.
     */
    public void empaquetarDatosAcademicos(ResidenteDTO dto) {

        // dificultades academicas
        if (chkAyudaSiempre.isSelected()) {
            dto.setBuscaAyudaAcademica("Siempre");
        } else if (chkAyudaAVeces.isSelected()) {
            dto.setBuscaAyudaAcademica("A veces");
        } else if (chkAyudaNunca.isSelected()) {
            dto.setBuscaAyudaAcademica("Nunca");
        } else {
            dto.setBuscaAyudaAcademica("No especificado");
        }

        // Efectividad de sus metodos de estudio
        if (chkEstudioMuyEfectivo.isSelected()) {
            dto.setEfectividadEstudio("Muy efectivo");
        } else if (chkEstudioRegular.isSelected()) {
            dto.setEfectividadEstudio("Regular");
        } else if (chkEstudioPoco.isSelected()) {
            dto.setEfectividadEstudio("Poco");
        } else {
            dto.setEfectividadEstudio("No especificado");
        }

        // efectividad en la administración de su tiempo
        if (chkTiempoMuyEfectivo.isSelected()) {
            dto.setEfectividadTiempo("Muy efectivo");
        } else if (chkTiempoRegular.isSelected()) {
            dto.setEfectividadTiempo("Regular");
        } else if (chkTiempoPoco.isSelected()) {
            dto.setEfectividadTiempo("Poco");
        } else {
            dto.setEfectividadTiempo("No especificado");
        }

        // aspectos que le gustaría mejorar
        dto.setAspectosMejoraAcademica(txaMejorasAcademicas.getText().trim());
    }

    //metodos ayudantes de validación
    private boolean campoEsValido(javax.swing.JTextField campo) {
        return !campo.getText().trim().isEmpty();
    }

    // para text area
    private boolean areaEsValida(javax.swing.JTextArea area) {
        boolean valido = !area.getText().trim().isEmpty();
        marcarError(area, valido);
        return valido;
    }

    private boolean comboEsValido(javax.swing.JComboBox combo) {
        return combo.getSelectedIndex() > 0 && !combo.getSelectedItem().toString().toLowerCase().contains("selecciona");
    }

    /**
     * Valida que al menos una opción de un grupo de check boxes haya sido
     * seleccionada. Si no se eligio ninguna, pinta todas las casillas del grupo
     */
    private boolean grupoChecksEsValido(javax.swing.JCheckBox... checks) {
        boolean alMenosUno = false;
        for (javax.swing.JCheckBox chk : checks) {
            if (chk.isSelected()) {
                alMenosUno = true;
                break;
            }
        }
        // Pintamos TODOS los del grupo
        for (javax.swing.JCheckBox chk : checks) {
            marcarError(chk, alMenosUno);
        }
        return alMenosUno;
    }

    /**
     * Revisa todos los campos del panel y pinta los que falten.
     */
    public boolean validarCampos() {
        boolean v1 = grupoChecksEsValido(chkAyudaSiempre, chkAyudaAVeces, chkAyudaNunca);
        boolean v2 = grupoChecksEsValido(chkEstudioMuyEfectivo, chkEstudioRegular, chkEstudioPoco);
        boolean v3 = grupoChecksEsValido(chkTiempoMuyEfectivo, chkTiempoRegular, chkTiempoPoco);
        boolean v4 = areaEsValida(txaMejorasAcademicas);

        if (!v1 || !v2 || !v3 || !v4) {
            return false;
        }

        return true;
    }

    /**
     * Este metodo recibe los datos de la base de datos y rellena los campos
     * visuales de aspectos académicos.
     */
    public void cargarDatosAcademicos(ResidenteDTO dto) {
        if (dto == null || dto.getCurp() == null || dto.getCurp().trim().isEmpty()) {
            return;
        }

        //preguntas de ayuda
        chkAyudaSiempre.setSelected("Siempre".equals(dto.getBuscaAyudaAcademica()));
        chkAyudaAVeces.setSelected("A veces".equals(dto.getBuscaAyudaAcademica()));
        chkAyudaNunca.setSelected("Nunca".equals(dto.getBuscaAyudaAcademica()));

        //efectividad de sus metodos de estudio
        chkEstudioMuyEfectivo.setSelected("Muy efectivo".equals(dto.getEfectividadEstudio()));
        chkEstudioRegular.setSelected("Regular".equals(dto.getEfectividadEstudio()));
        chkEstudioPoco.setSelected("Poco".equals(dto.getEfectividadEstudio()));

        //efectividad en la administracion de su tiempo
        chkTiempoMuyEfectivo.setSelected("Muy efectivo".equals(dto.getEfectividadTiempo()));
        chkTiempoRegular.setSelected("Regular".equals(dto.getEfectividadTiempo()));
        chkTiempoPoco.setSelected("Poco".equals(dto.getEfectividadTiempo()));

        //aspectos que le gustaria mejorar
        txaMejorasAcademicas.setText(dto.getAspectosMejoraAcademica());
    }

    /**
     * Metodo ayudante que recibe cualquier cantidad de CheckBoxes y los mete en
     * un mismo grupo para poder seleccionar uno y mas
     */
    private void crearGrupo(javax.swing.JCheckBox... casillas) {
        javax.swing.ButtonGroup grupo = new javax.swing.ButtonGroup();
        for (javax.swing.JCheckBox casilla : casillas) {
            grupo.add(casilla);
        }
    }

    private void agruparCasillas() {
        crearGrupo(chkAyudaSiempre, chkAyudaAVeces, chkAyudaNunca);
        crearGrupo(chkEstudioMuyEfectivo, chkEstudioRegular, chkEstudioPoco);
        crearGrupo(chkTiempoMuyEfectivo, chkTiempoRegular, chkTiempoPoco);
    }

    /**
     * Pinta el fondo de cualquier dato de color si hay error.
     */
    private void marcarError(javax.swing.JComponent componente, boolean valido) {
        if (componente instanceof javax.swing.JCheckBox || componente instanceof javax.swing.JRadioButton) {
            componente.setOpaque(true);
        }

        if (valido) {
            if (componente instanceof javax.swing.JCheckBox) {
                componente.setBackground(null);
            } else {
                componente.setBackground(java.awt.Color.WHITE);
            }
        } else {
            componente.setBackground(new java.awt.Color(255, 235, 235));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAyudaAVeces;
    private javax.swing.JCheckBox chkAyudaNunca;
    private javax.swing.JCheckBox chkAyudaSiempre;
    private javax.swing.JCheckBox chkEstudioMuyEfectivo;
    private javax.swing.JCheckBox chkEstudioPoco;
    private javax.swing.JCheckBox chkEstudioRegular;
    private javax.swing.JCheckBox chkTiempoMuyEfectivo;
    private javax.swing.JCheckBox chkTiempoPoco;
    private javax.swing.JCheckBox chkTiempoRegular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarAyuda;
    private javax.swing.JLabel lblEfectividadEstudio;
    private javax.swing.JLabel lblEfectividadTiempo;
    private javax.swing.JLabel lblMejorasAcademicas;
    private javax.swing.JLabel lblMejorasAcademicas2;
    private javax.swing.JLabel lblTituloAcademicos;
    private javax.swing.JTextArea txaMejorasAcademicas;
    // End of variables declaration//GEN-END:variables
}
