/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author User
 */
public class pnlAspAcademicos extends javax.swing.JPanel {

    /**
     * Creates new form pnlAspAcademicos
     */
    public pnlAspAcademicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloAcademicos = new javax.swing.JLabel();
        lblBuscarAyuda = new javax.swing.JLabel();
        lblMejorasAcademicas = new javax.swing.JLabel();
        lblMejorasAcademicas2 = new javax.swing.JLabel();
        lblEfectividadTiempo = new javax.swing.JLabel();
        lblEfectividadEstudio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMejorasAcademicas = new javax.swing.JTextArea();
        chkAyudaNunca = new javax.swing.JCheckBox();
        chkTiempoMuyEfectivo = new javax.swing.JCheckBox();
        chkAyudaAVeces = new javax.swing.JCheckBox();
        chkAyudaSiempre = new javax.swing.JCheckBox();
        chkTiempoPoco = new javax.swing.JCheckBox();
        chkTiempoRegular = new javax.swing.JCheckBox();
        chkEstudioPoco = new javax.swing.JCheckBox();
        chkEstudioRegular = new javax.swing.JCheckBox();
        chkEstudioMuyEfectivo = new javax.swing.JCheckBox();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloAcademicos.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloAcademicos.setText("Aspectos académicos");
        jPanel1.add(lblTituloAcademicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        lblBuscarAyuda.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblBuscarAyuda.setText("¿Sueles buscar ayuda académica cuando la necesitas?");
        jPanel1.add(lblBuscarAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 480, -1));

        lblMejorasAcademicas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblMejorasAcademicas.setText("Aspectos académicos en los que te gustaría prepararte mejor");
        jPanel1.add(lblMejorasAcademicas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        lblMejorasAcademicas2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblMejorasAcademicas2.setText("(administración del tiempo, orientación vocacional, técnicas de estudio, etc.).");
        jPanel1.add(lblMejorasAcademicas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));

        lblEfectividadTiempo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEfectividadTiempo.setText("Efectividad en la administración del tiempo:");
        jPanel1.add(lblEfectividadTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        lblEfectividadEstudio.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEfectividadEstudio.setText("Efectividad de tu método de estudio:");
        jPanel1.add(lblEfectividadEstudio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        txaMejorasAcademicas.setColumns(20);
        txaMejorasAcademicas.setRows(5);
        jScrollPane1.setViewportView(txaMejorasAcademicas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 286, 330, 80));

        chkAyudaNunca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAyudaNunca.setText("Casi nunca");
        chkAyudaNunca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAyudaNuncaActionPerformed(evt);
            }
        });
        jPanel1.add(chkAyudaNunca, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, -1, -1));

        chkTiempoMuyEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkTiempoMuyEfectivo.setText("Muy efectivo");
        chkTiempoMuyEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTiempoMuyEfectivoActionPerformed(evt);
            }
        });
        jPanel1.add(chkTiempoMuyEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, -1, -1));

        chkAyudaAVeces.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAyudaAVeces.setText("A veces");
        chkAyudaAVeces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAyudaAVecesActionPerformed(evt);
            }
        });
        jPanel1.add(chkAyudaAVeces, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 140, -1, -1));

        chkAyudaSiempre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAyudaSiempre.setText("Casi siempre");
        chkAyudaSiempre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAyudaSiempreActionPerformed(evt);
            }
        });
        jPanel1.add(chkAyudaSiempre, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        chkTiempoPoco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkTiempoPoco.setText("Poco efectivo");
        chkTiempoPoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTiempoPocoActionPerformed(evt);
            }
        });
        jPanel1.add(chkTiempoPoco, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, -1, -1));

        chkTiempoRegular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkTiempoRegular.setText("Regular");
        chkTiempoRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkTiempoRegularActionPerformed(evt);
            }
        });
        jPanel1.add(chkTiempoRegular, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, -1, -1));

        chkEstudioPoco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkEstudioPoco.setText("Poco efectivo");
        chkEstudioPoco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstudioPocoActionPerformed(evt);
            }
        });
        jPanel1.add(chkEstudioPoco, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, -1, -1));

        chkEstudioRegular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkEstudioRegular.setText("Regular");
        chkEstudioRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstudioRegularActionPerformed(evt);
            }
        });
        jPanel1.add(chkEstudioRegular, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, -1, -1));

        chkEstudioMuyEfectivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkEstudioMuyEfectivo.setText("Muy efectivo");
        chkEstudioMuyEfectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEstudioMuyEfectivoActionPerformed(evt);
            }
        });
        jPanel1.add(chkEstudioMuyEfectivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkAyudaNuncaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAyudaNuncaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAyudaNuncaActionPerformed

    private void chkTiempoMuyEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTiempoMuyEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTiempoMuyEfectivoActionPerformed

    private void chkAyudaAVecesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAyudaAVecesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAyudaAVecesActionPerformed

    private void chkAyudaSiempreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAyudaSiempreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAyudaSiempreActionPerformed

    private void chkTiempoPocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTiempoPocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTiempoPocoActionPerformed

    private void chkTiempoRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkTiempoRegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkTiempoRegularActionPerformed

    private void chkEstudioPocoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstudioPocoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstudioPocoActionPerformed

    private void chkEstudioRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstudioRegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstudioRegularActionPerformed

    private void chkEstudioMuyEfectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEstudioMuyEfectivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkEstudioMuyEfectivoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAyudaAVeces;
    private javax.swing.JCheckBox chkAyudaNunca;
    private javax.swing.JCheckBox chkAyudaSiempre;
    private javax.swing.JCheckBox chkEstudioMuyEfectivo;
    private javax.swing.JCheckBox chkEstudioPoco;
    private javax.swing.JCheckBox chkEstudioRegular;
    private javax.swing.JCheckBox chkTiempoMuyEfectivo;
    private javax.swing.JCheckBox chkTiempoPoco;
    private javax.swing.JCheckBox chkTiempoRegular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscarAyuda;
    private javax.swing.JLabel lblEfectividadEstudio;
    private javax.swing.JLabel lblEfectividadTiempo;
    private javax.swing.JLabel lblMejorasAcademicas;
    private javax.swing.JLabel lblMejorasAcademicas2;
    private javax.swing.JLabel lblTituloAcademicos;
    private javax.swing.JTextArea txaMejorasAcademicas;
    // End of variables declaration//GEN-END:variables
}
