/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author User
 */
public class pnlAspPersonales extends javax.swing.JPanel {

    /**
     * Creates new form pnlAspPersonales
     */
    public pnlAspPersonales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblVividoFuera = new javax.swing.JLabel();
        chkVividoFueraSi = new javax.swing.JCheckBox();
        chkVividoFueraNo = new javax.swing.JCheckBox();
        txtTiempoVividoFuera = new javax.swing.JTextField();
        lblTiempoVividoFuera = new javax.swing.JLabel();
        lblDecisionResidencia = new javax.swing.JLabel();
        chkDecisionTuya = new javax.swing.JCheckBox();
        chkDecisionPadres = new javax.swing.JCheckBox();
        chkDecisionAmbos = new javax.swing.JCheckBox();
        lblDecisionResidencia2 = new javax.swing.JLabel();
        lblRazonesVivir = new javax.swing.JLabel();
        lblRazonesVivir2 = new javax.swing.JLabel();
        lblAdaptacion = new javax.swing.JLabel();
        txtRespuestaApdc4 = new javax.swing.JTextField();
        chkAdaptacionDificil = new javax.swing.JCheckBox();
        chkAdaptacionRegular = new javax.swing.JCheckBox();
        chkAdaptacionFacil = new javax.swing.JCheckBox();
        chkConvivenciaPersuadir = new javax.swing.JCheckBox();
        chkConvivenciaNegociar = new javax.swing.JCheckBox();
        chkConvivenciaCeder = new javax.swing.JCheckBox();
        lblEstiloConvivencia = new javax.swing.JLabel();
        lblSituacionesNoDeseadas = new javax.swing.JLabel();
        txtSituacionesNoDeseadas = new javax.swing.JTextField();
        lblSituacionesNoDeseadas2 = new javax.swing.JLabel();
        lblCaracteristicasCompanero = new javax.swing.JLabel();
        chkCompaneroExtranjero = new javax.swing.JCheckBox();
        chkCompaneroMexicano = new javax.swing.JCheckBox();
        chkCompaneroReingreso = new javax.swing.JCheckBox();
        lblHoraDormir = new javax.swing.JLabel();
        cmbxHoraDormir = new javax.swing.JComboBox<>();
        lblToleraRuido = new javax.swing.JLabel();
        lblImportanciaOrden = new javax.swing.JLabel();
        lblHabitosHigiene = new javax.swing.JLabel();
        lblObjetosTraer = new javax.swing.JLabel();
        chkObjetoAuto = new javax.swing.JCheckBox();
        chkObjetoComputadora = new javax.swing.JCheckBox();
        chkToleraRuidoSi = new javax.swing.JCheckBox();
        chkToleraRuidoNo = new javax.swing.JCheckBox();
        chkOrdenPoco = new javax.swing.JCheckBox();
        chkHigienePoco = new javax.swing.JCheckBox();
        chkOrdenRegular = new javax.swing.JCheckBox();
        chkHigieneRegular = new javax.swing.JCheckBox();
        chkOrdenMucho = new javax.swing.JCheckBox();
        chkHigieneEstricto = new javax.swing.JCheckBox();
        chkObjetoTV = new javax.swing.JCheckBox();
        chkObjetoFrigobar = new javax.swing.JCheckBox();
        lblActividadesIniciativa = new javax.swing.JLabel();
        chkIniciativaSi = new javax.swing.JCheckBox();
        chkIniciativaNo = new javax.swing.JCheckBox();
        chkIniciativaAveses = new javax.swing.JCheckBox();
        lblParticipacionGrupo = new javax.swing.JLabel();
        lblTipoGrupo = new javax.swing.JLabel();
        lblActividadesRealizadas = new javax.swing.JLabel();
        lblActividadesDeseadas = new javax.swing.JLabel();
        lblActividadesRealizad2as = new javax.swing.JLabel();
        cmbxTipoGrupo = new javax.swing.JComboBox<>();
        chkGrupoSi = new javax.swing.JCheckBox();
        chkGrupoNo = new javax.swing.JCheckBox();
        txtActividadesRealizadas = new javax.swing.JTextField();
        chkDeseaDeportivas = new javax.swing.JCheckBox();
        chkDeseaCulturales = new javax.swing.JCheckBox();
        chkDeseaArtisticas = new javax.swing.JCheckBox();
        cmbxAspectosMejora = new javax.swing.JComboBox<>();
        txaOtraInformacion = new javax.swing.JTextField();
        lblOtraInformacion = new javax.swing.JLabel();
        lblAspectosMejora = new javax.swing.JLabel();
        lblAspectosMejora2 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setText("Datos de aspectos personales y de convivencia");

        lblVividoFuera.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblVividoFuera.setText("¿Has vivido fuera de tu casa anteriormente?");

        chkVividoFueraSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkVividoFueraSi.setText("SI");

        chkVividoFueraNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkVividoFueraNo.setText("NO");

        lblTiempoVividoFuera.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTiempoVividoFuera.setText("Si tu respuesta es sí, ¿por cuánto tiempo?");

        lblDecisionResidencia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDecisionResidencia.setText("La decisión de vivir en Residencias ");

        chkDecisionTuya.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkDecisionTuya.setText("Tuya");

        chkDecisionPadres.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkDecisionPadres.setText("Tus Padres");

        chkDecisionAmbos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkDecisionAmbos.setText("Ambos");

        lblDecisionResidencia2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDecisionResidencia2.setText("estudiantiles es principalmente:");

        lblRazonesVivir.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblRazonesVivir.setText("Razones principales por las que solicitas");

        lblRazonesVivir2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblRazonesVivir2.setText(" vivir en la residencia");

        lblAdaptacion.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblAdaptacion.setText("Adaptación a nuevas situaciones de convivencia:");

        chkAdaptacionDificil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAdaptacionDificil.setText("Dificilmente");
        chkAdaptacionDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAdaptacionDificilActionPerformed(evt);
            }
        });

        chkAdaptacionRegular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAdaptacionRegular.setText("Regularmente");

        chkAdaptacionFacil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAdaptacionFacil.setText("Facilmente");

        chkConvivenciaPersuadir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkConvivenciaPersuadir.setText("Persuadir");

        chkConvivenciaNegociar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkConvivenciaNegociar.setText("Negociar");

        chkConvivenciaCeder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkConvivenciaCeder.setText("Ceder");
        chkConvivenciaCeder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkConvivenciaCederActionPerformed(evt);
            }
        });

        lblEstiloConvivencia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEstiloConvivencia.setText("En la convivencia con otros, generalmente  prefieres:");

        lblSituacionesNoDeseadas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblSituacionesNoDeseadas.setText("Cosas o situaciones que NO te gustaría ");

        lblSituacionesNoDeseadas2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblSituacionesNoDeseadas2.setText("vivir durante la convivencia:");

        lblCaracteristicasCompanero.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCaracteristicasCompanero.setText("Características deseadas en el compañero de habitación:");

        chkCompaneroExtranjero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkCompaneroExtranjero.setText("Extranjero");
        chkCompaneroExtranjero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCompaneroExtranjeroActionPerformed(evt);
            }
        });

        chkCompaneroMexicano.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkCompaneroMexicano.setText("Méxicano");

        chkCompaneroReingreso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkCompaneroReingreso.setText("Reingreso");

        lblHoraDormir.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblHoraDormir.setText("Hora en que acostumbras dormirte:");

        cmbxHoraDormir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbxHoraDormir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una hora", "9:00pm", "10:00pm", "11:00pm", "12:00am", "1:00am" }));

        lblToleraRuido.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblToleraRuido.setText("¿Toleras cierto ruido al estudiar?");

        lblImportanciaOrden.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblImportanciaOrden.setText("Nivel de importancia del orden:");

        lblHabitosHigiene.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblHabitosHigiene.setText("Hábitos de higiene:");

        lblObjetosTraer.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblObjetosTraer.setText("Objetos que traerás:");

        chkObjetoAuto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkObjetoAuto.setText("Auto");
        chkObjetoAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkObjetoAutoActionPerformed(evt);
            }
        });

        chkObjetoComputadora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkObjetoComputadora.setText("Computadora");

        chkToleraRuidoSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkToleraRuidoSi.setText("SI");

        chkToleraRuidoNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkToleraRuidoNo.setText("NO");

        chkOrdenPoco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkOrdenPoco.setText("Poco");

        chkHigienePoco.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkHigienePoco.setText("Poco");

        chkOrdenRegular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkOrdenRegular.setText("Regular");

        chkHigieneRegular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkHigieneRegular.setText("Regulares");

        chkOrdenMucho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkOrdenMucho.setText("Muy importante");

        chkHigieneEstricto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkHigieneEstricto.setText("Muy estrictos");

        chkObjetoTV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkObjetoTV.setText("TV");

        chkObjetoFrigobar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkObjetoFrigobar.setText("Frigobar");

        lblActividadesIniciativa.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblActividadesIniciativa.setText("¿Participas en actividades por iniciativa propia?");

        chkIniciativaSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkIniciativaSi.setText("SI");

        chkIniciativaNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkIniciativaNo.setText("NO");

        chkIniciativaAveses.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkIniciativaAveses.setText("Algunas veces");

        lblParticipacionGrupo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblParticipacionGrupo.setText("¿Has participado en algún grupo, club o equipo?");

        lblTipoGrupo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTipoGrupo.setText("Tipo de grupo:");

        lblActividadesRealizadas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblActividadesRealizadas.setText("Actividades realizadas relacionadas con la ");

        lblActividadesDeseadas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblActividadesDeseadas.setText("Actividades que te gustaría realizar en Residencias:");

        lblActividadesRealizad2as.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblActividadesRealizad2as.setText("pregunta anterior:");

        cmbxTipoGrupo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbxTipoGrupo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un tipo de grupo", "Deportivo", "Cultural", "Religioso" }));

        chkGrupoSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkGrupoSi.setText("SI");

        chkGrupoNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkGrupoNo.setText("NO");

        chkDeseaDeportivas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkDeseaDeportivas.setText("Deportivas");

        chkDeseaCulturales.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkDeseaCulturales.setText("Culturales");

        chkDeseaArtisticas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkDeseaArtisticas.setText("Artisticas");

        cmbxAspectosMejora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbxAspectosMejora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un aspecto", "Comunicación", "Habilidades blancas", "Compañerismo", "Autoevaluación" }));

        txaOtraInformacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txaOtraInformacionFocusLost(evt);
            }
        });

        lblOtraInformacion.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblOtraInformacion.setText("Otra información importante sobre ti:");

        lblAspectosMejora.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblAspectosMejora.setText("Aspectos en los que te gustaría prepararte ");

        lblAspectosMejora2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblAspectosMejora2.setText("mejor o conocer más:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblVividoFuera)
                .addGap(132, 132, 132)
                .addComponent(chkVividoFueraSi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(chkVividoFueraNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblTiempoVividoFuera)
                .addGap(153, 153, 153)
                .addComponent(txtTiempoVividoFuera, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDecisionResidencia)
                    .addComponent(lblDecisionResidencia2))
                .addGap(210, 210, 210)
                .addComponent(chkDecisionTuya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(chkDecisionPadres, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(chkDecisionAmbos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRazonesVivir)
                    .addComponent(lblRazonesVivir2))
                .addGap(163, 163, 163)
                .addComponent(txtRespuestaApdc4, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblAdaptacion)
                .addGap(90, 90, 90)
                .addComponent(chkAdaptacionDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(chkAdaptacionRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(chkAdaptacionFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblEstiloConvivencia)
                .addGap(54, 54, 54)
                .addComponent(chkConvivenciaCeder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(chkConvivenciaNegociar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(chkConvivenciaPersuadir, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSituacionesNoDeseadas2)
                    .addComponent(lblSituacionesNoDeseadas))
                .addGap(166, 166, 166)
                .addComponent(txtSituacionesNoDeseadas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblCaracteristicasCompanero)
                .addGap(18, 18, 18)
                .addComponent(chkCompaneroExtranjero, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(chkCompaneroMexicano, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(chkCompaneroReingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblHoraDormir)
                .addGap(202, 202, 202)
                .addComponent(cmbxHoraDormir, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblToleraRuido)
                .addGap(232, 232, 232)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(chkToleraRuidoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chkToleraRuidoSi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblImportanciaOrden)
                .addGap(240, 240, 240)
                .addComponent(chkOrdenPoco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(chkOrdenRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(chkOrdenMucho, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblHabitosHigiene)
                .addGap(349, 349, 349)
                .addComponent(chkHigienePoco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(chkHigieneRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(chkHigieneEstricto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblObjetosTraer)
                .addGap(341, 341, 341)
                .addComponent(chkObjetoAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(chkObjetoComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(chkObjetoTV, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(chkObjetoFrigobar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblActividadesIniciativa)
                .addGap(102, 102, 102)
                .addComponent(chkIniciativaSi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(chkIniciativaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(chkIniciativaAveses, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblParticipacionGrupo)
                .addGap(86, 86, 86)
                .addComponent(chkGrupoSi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(chkGrupoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblTipoGrupo)
                .addGap(389, 389, 389)
                .addComponent(cmbxTipoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblActividadesRealizadas)
                    .addComponent(lblActividadesRealizad2as))
                .addGap(142, 142, 142)
                .addComponent(txtActividadesRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblActividadesDeseadas)
                .addGap(70, 70, 70)
                .addComponent(chkDeseaDeportivas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(chkDeseaCulturales, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(chkDeseaArtisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAspectosMejora2)
                    .addComponent(lblAspectosMejora))
                .addGap(138, 138, 138)
                .addComponent(cmbxAspectosMejora, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblOtraInformacion)
                .addGap(187, 187, 187)
                .addComponent(txaOtraInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblVividoFuera)
                    .addComponent(chkVividoFueraSi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkVividoFueraNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTiempoVividoFuera)
                    .addComponent(txtTiempoVividoFuera, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDecisionResidencia)
                        .addGap(3, 3, 3)
                        .addComponent(lblDecisionResidencia2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkDecisionTuya, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkDecisionPadres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkDecisionAmbos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRazonesVivir)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblRazonesVivir2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtRespuestaApdc4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdaptacion)
                    .addComponent(chkAdaptacionDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAdaptacionRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkAdaptacionFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstiloConvivencia)
                    .addComponent(chkConvivenciaCeder, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkConvivenciaNegociar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkConvivenciaPersuadir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblSituacionesNoDeseadas2))
                    .addComponent(lblSituacionesNoDeseadas)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtSituacionesNoDeseadas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCaracteristicasCompanero)
                    .addComponent(chkCompaneroExtranjero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkCompaneroMexicano, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkCompaneroReingreso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHoraDormir)
                    .addComponent(cmbxHoraDormir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblToleraRuido)
                    .addComponent(chkToleraRuidoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkToleraRuidoSi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImportanciaOrden)
                    .addComponent(chkOrdenPoco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkOrdenRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkOrdenMucho, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHabitosHigiene)
                    .addComponent(chkHigienePoco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkHigieneRegular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkHigieneEstricto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObjetosTraer)
                    .addComponent(chkObjetoAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkObjetoComputadora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkObjetoTV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkObjetoFrigobar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblActividadesIniciativa)
                    .addComponent(chkIniciativaSi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkIniciativaNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkIniciativaAveses, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblParticipacionGrupo)
                    .addComponent(chkGrupoSi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkGrupoNo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoGrupo)
                    .addComponent(cmbxTipoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblActividadesRealizadas)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblActividadesRealizad2as))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtActividadesRealizadas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblActividadesDeseadas)
                    .addComponent(chkDeseaDeportivas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkDeseaCulturales, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkDeseaArtisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(lblAspectosMejora2))
                    .addComponent(lblAspectosMejora)
                    .addComponent(cmbxAspectosMejora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOtraInformacion)
                    .addComponent(txaOtraInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkAdaptacionDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAdaptacionDificilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAdaptacionDificilActionPerformed

    private void chkConvivenciaCederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkConvivenciaCederActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkConvivenciaCederActionPerformed

    private void chkCompaneroExtranjeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCompaneroExtranjeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCompaneroExtranjeroActionPerformed

    private void chkObjetoAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkObjetoAutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkObjetoAutoActionPerformed

    private void txaOtraInformacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txaOtraInformacionFocusLost
//        if (!txtApdcInfoResi20.getText().trim().isEmpty()) {
//            mostrarSeccion(JpnlAspectosAcademicos);
//        }
    }//GEN-LAST:event_txaOtraInformacionFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAdaptacionDificil;
    private javax.swing.JCheckBox chkAdaptacionFacil;
    private javax.swing.JCheckBox chkAdaptacionRegular;
    private javax.swing.JCheckBox chkCompaneroExtranjero;
    private javax.swing.JCheckBox chkCompaneroMexicano;
    private javax.swing.JCheckBox chkCompaneroReingreso;
    private javax.swing.JCheckBox chkConvivenciaCeder;
    private javax.swing.JCheckBox chkConvivenciaNegociar;
    private javax.swing.JCheckBox chkConvivenciaPersuadir;
    private javax.swing.JCheckBox chkDecisionAmbos;
    private javax.swing.JCheckBox chkDecisionPadres;
    private javax.swing.JCheckBox chkDecisionTuya;
    private javax.swing.JCheckBox chkDeseaArtisticas;
    private javax.swing.JCheckBox chkDeseaCulturales;
    private javax.swing.JCheckBox chkDeseaDeportivas;
    private javax.swing.JCheckBox chkGrupoNo;
    private javax.swing.JCheckBox chkGrupoSi;
    private javax.swing.JCheckBox chkHigieneEstricto;
    private javax.swing.JCheckBox chkHigienePoco;
    private javax.swing.JCheckBox chkHigieneRegular;
    private javax.swing.JCheckBox chkIniciativaAveses;
    private javax.swing.JCheckBox chkIniciativaNo;
    private javax.swing.JCheckBox chkIniciativaSi;
    private javax.swing.JCheckBox chkObjetoAuto;
    private javax.swing.JCheckBox chkObjetoComputadora;
    private javax.swing.JCheckBox chkObjetoFrigobar;
    private javax.swing.JCheckBox chkObjetoTV;
    private javax.swing.JCheckBox chkOrdenMucho;
    private javax.swing.JCheckBox chkOrdenPoco;
    private javax.swing.JCheckBox chkOrdenRegular;
    private javax.swing.JCheckBox chkToleraRuidoNo;
    private javax.swing.JCheckBox chkToleraRuidoSi;
    private javax.swing.JCheckBox chkVividoFueraNo;
    private javax.swing.JCheckBox chkVividoFueraSi;
    private javax.swing.JComboBox<String> cmbxAspectosMejora;
    private javax.swing.JComboBox<String> cmbxHoraDormir;
    private javax.swing.JComboBox<String> cmbxTipoGrupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblActividadesDeseadas;
    private javax.swing.JLabel lblActividadesIniciativa;
    private javax.swing.JLabel lblActividadesRealizad2as;
    private javax.swing.JLabel lblActividadesRealizadas;
    private javax.swing.JLabel lblAdaptacion;
    private javax.swing.JLabel lblAspectosMejora;
    private javax.swing.JLabel lblAspectosMejora2;
    private javax.swing.JLabel lblCaracteristicasCompanero;
    private javax.swing.JLabel lblDecisionResidencia;
    private javax.swing.JLabel lblDecisionResidencia2;
    private javax.swing.JLabel lblEstiloConvivencia;
    private javax.swing.JLabel lblHabitosHigiene;
    private javax.swing.JLabel lblHoraDormir;
    private javax.swing.JLabel lblImportanciaOrden;
    private javax.swing.JLabel lblObjetosTraer;
    private javax.swing.JLabel lblOtraInformacion;
    private javax.swing.JLabel lblParticipacionGrupo;
    private javax.swing.JLabel lblRazonesVivir;
    private javax.swing.JLabel lblRazonesVivir2;
    private javax.swing.JLabel lblSituacionesNoDeseadas;
    private javax.swing.JLabel lblSituacionesNoDeseadas2;
    private javax.swing.JLabel lblTiempoVividoFuera;
    private javax.swing.JLabel lblTipoGrupo;
    private javax.swing.JLabel lblToleraRuido;
    private javax.swing.JLabel lblVividoFuera;
    private javax.swing.JTextField txaOtraInformacion;
    private javax.swing.JTextField txtActividadesRealizadas;
    private javax.swing.JTextField txtRespuestaApdc4;
    private javax.swing.JTextField txtSituacionesNoDeseadas;
    private javax.swing.JTextField txtTiempoVividoFuera;
    // End of variables declaration//GEN-END:variables
}
