package Presentacion;

import Negocio.DTOs.ResidenteDTO;

/**
 *
 * @author Valeria
 */
public class pnlContactoEmergencia extends javax.swing.JPanel {

    /**
     * Creates new form pnlEmergencia
     */
    public pnlContactoEmergencia() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloEmergencia = new javax.swing.JLabel();
        lblNombreEmergencia = new javax.swing.JLabel();
        lblCorreoEmergencia = new javax.swing.JLabel();
        txtCorreoEmergencia = new javax.swing.JTextField();
        txtNombreEmergencia = new javax.swing.JTextField();
        lblCiudadEstadoPaisEmergencia = new javax.swing.JLabel();
        lblTelefonoEmergencia = new javax.swing.JLabel();
        txtTelefonoEmergencia = new javax.swing.JTextField();
        cmbCodigoPaisEmergencia = new javax.swing.JComboBox<>();
        lblCelularEmergencia = new javax.swing.JLabel();
        txtCiudadEstadoPaisEmergencia = new javax.swing.JTextField();
        txtCelularEmergencia = new javax.swing.JTextField();
        lblDomicilioEmergencia = new javax.swing.JLabel();
        lblParentescoEmergencia = new javax.swing.JLabel();
        txtDomicilioEmergencia = new javax.swing.JTextField();
        cmbParentescoEmergencia = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloEmergencia.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloEmergencia.setText("Datos de contacto en caso de emergencia");

        lblNombreEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblNombreEmergencia.setText("Nombre completo:");

        lblCorreoEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCorreoEmergencia.setText("Correo:");

        txtNombreEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreEmergenciaActionPerformed(evt);
            }
        });

        lblCiudadEstadoPaisEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCiudadEstadoPaisEmergencia.setText("Ciudad, Estado y País de residencia:");

        lblTelefonoEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTelefonoEmergencia.setText("Telefono:");

        cmbCodigoPaisEmergencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+52", "+67", "+55", "+30", "+33", "+48" }));

        lblCelularEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCelularEmergencia.setText("Celular:");

        txtCelularEmergencia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelularEmergenciaFocusLost(evt);
            }
        });

        lblDomicilioEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDomicilioEmergencia.setText("Domicilio:");

        lblParentescoEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblParentescoEmergencia.setText("Parentesco:");

        txtDomicilioEmergencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomicilioEmergenciaActionPerformed(evt);
            }
        });

        cmbParentescoEmergencia.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbParentescoEmergencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un parentesco", "Padre", "Madre", "Hermano", "Abuela/Abuelo", "Tutor legal" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTituloEmergencia))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblNombreEmergencia)
                .addGap(11, 11, 11)
                .addComponent(txtNombreEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(lblParentescoEmergencia)
                .addGap(18, 18, 18)
                .addComponent(cmbParentescoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblDomicilioEmergencia)
                .addGap(21, 21, 21)
                .addComponent(txtDomicilioEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblCiudadEstadoPaisEmergencia)
                .addGap(15, 15, 15)
                .addComponent(txtCiudadEstadoPaisEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblCelularEmergencia)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCodigoPaisEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txtCelularEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addComponent(lblTelefonoEmergencia)
                .addGap(28, 28, 28)
                .addComponent(txtTelefonoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblCorreoEmergencia)
                .addGap(15, 15, 15)
                .addComponent(txtCorreoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloEmergencia)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreEmergencia)
                    .addComponent(txtNombreEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParentescoEmergencia)
                    .addComponent(cmbParentescoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDomicilioEmergencia)
                    .addComponent(txtDomicilioEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCiudadEstadoPaisEmergencia)
                    .addComponent(txtCiudadEstadoPaisEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCelularEmergencia)
                    .addComponent(cmbCodigoPaisEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCelularEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoEmergencia)
                    .addComponent(txtTelefonoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreoEmergencia)
                    .addComponent(txtCorreoEmergencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreEmergenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEmergenciaActionPerformed

    private void txtCelularEmergenciaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelularEmergenciaFocusLost
        //        if (!txtCelularSoli.getText().trim().isEmpty()) {
        //            mostrarSeccion(JpnlDatosTutor);
        //        }
    }//GEN-LAST:event_txtCelularEmergenciaFocusLost

    private void txtDomicilioEmergenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomicilioEmergenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioEmergenciaActionPerformed

    /**
     * Metodo para guardar losdatos en el DTO.
     */
    public void empaquetarDatosEmergencia(ResidenteDTO dto) {

        dto.setNombreEmergencia(txtNombreEmergencia.getText().trim());

        // Manejo del Parentesco de Emergencia
        String parentesco = cmbParentescoEmergencia.getSelectedItem().toString();
        // valida si dice "Selecciona un parentesco" o algo similar
        if (parentesco.toLowerCase().contains("selecciona")) {
            dto.setParentescoEmergencia("");
        } else {
            dto.setParentescoEmergencia(parentesco);
        }

        dto.setDomicilioEmergencia(txtDomicilioEmergencia.getText().trim());

        //ciudad, estado y país
        dto.setLugarEmergencia(txtCiudadEstadoPaisEmergencia.getText().trim());

        //concatenar el código de país con el celular
        String codigoPais = cmbCodigoPaisEmergencia.getSelectedItem().toString();
        dto.setCelularEmergencia(codigoPais + " " + txtCelularEmergencia.getText().trim());

        dto.setTelefonoEmergencia(txtTelefonoEmergencia.getText().trim());
        dto.setCorreoEmergencia(txtCorreoEmergencia.getText().trim());
    }
    
    /**
     * Este metodo recibe un DTO y rellena los campos automáticamente.
     */
    public void cargarDatosEmergencia(ResidenteDTO dto) {
        if (dto == null) return;

        txtNombreEmergencia.setText(dto.getNombreEmergencia() != null ? dto.getNombreEmergencia() : "");
        txtDomicilioEmergencia.setText(dto.getDomicilioEmergencia() != null ? dto.getDomicilioEmergencia() : "");
        txtCiudadEstadoPaisEmergencia.setText(dto.getLugarEmergencia() != null ? dto.getLugarEmergencia() : "");
        txtCelularEmergencia.setText(dto.getCelularEmergencia() != null ? dto.getCelularEmergencia() : "");
        txtTelefonoEmergencia.setText(dto.getTelefonoEmergencia() != null ? dto.getTelefonoEmergencia() : "");
        txtCorreoEmergencia.setText(dto.getCorreoEmergencia() != null ? dto.getCorreoEmergencia() : "");

        if (dto.getParentescoEmergencia() != null) {
            cmbParentescoEmergencia.setSelectedItem(dto.getParentescoEmergencia());
        }
    }

    //metodos ayudantes de validación
    private boolean campoEsValido(javax.swing.JTextField campo) {
        return !campo.getText().trim().isEmpty();
    }

    private boolean areaEsValida(javax.swing.JTextArea area) {
        return !area.getText().trim().isEmpty();
    }

    private boolean comboEsValido(javax.swing.JComboBox combo) {
        return combo.getSelectedIndex() > 0 && !combo.getSelectedItem().toString().toLowerCase().contains("selecciona");
    }

    private boolean campoCondicionalEsValido(javax.swing.JCheckBox checkSi, javax.swing.JTextField campo) {
        if (checkSi.isSelected()) {
            return campoEsValido(campo);
        }
        return true;
    }

    public boolean validarCampos() {
        boolean todoValido = true;

        if (!campoEsValido(txtNombreEmergencia)) {
            todoValido = false;
        }
        if (!comboEsValido(cmbParentescoEmergencia)) {
            todoValido = false;
        }
        if (!campoEsValido(txtDomicilioEmergencia)) {
            todoValido = false;
        }
        if (!campoEsValido(txtCiudadEstadoPaisEmergencia)) {
            todoValido = false;
        }
        if (!campoEsValido(txtCelularEmergencia)) {
            todoValido = false;
        }
        if (!campoEsValido(txtTelefonoEmergencia)) {
            todoValido = false;
        }
        if (!campoEsValido(txtCorreoEmergencia)) {
            todoValido = false;
        }

        return todoValido;
    }

    /**
     * Este método recibe los datos de la base de datos y rellena los campos
     * visuales de Emergencia.
     */
    public void cargarDatos(ResidenteDTO dto) {
        if (dto == null) {
            return;
        }

        txtNombreEmergencia.setText(dto.getNombreEmergencia());

        if (dto.getParentescoEmergencia() != null && !dto.getParentescoEmergencia().isEmpty()) {
            cmbParentescoEmergencia.setSelectedItem(dto.getParentescoEmergencia());
        } else {
            cmbParentescoEmergencia.setSelectedIndex(0);
        }

        txtDomicilioEmergencia.setText(dto.getDomicilioEmergencia());
        txtCiudadEstadoPaisEmergencia.setText(dto.getLugarEmergencia());

        String celular = dto.getCelularEmergencia();
        if (celular != null && celular.contains(" ")) {
            String[] partes = celular.split(" ", 2);
            cmbCodigoPaisEmergencia.setSelectedItem(partes[0]);
            txtCelularEmergencia.setText(partes[1]);
        } else {
            txtCelularEmergencia.setText(celular);
        }

        txtTelefonoEmergencia.setText(dto.getTelefonoEmergencia());
        txtCorreoEmergencia.setText(dto.getCorreoEmergencia());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCodigoPaisEmergencia;
    private javax.swing.JComboBox<String> cmbParentescoEmergencia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCelularEmergencia;
    private javax.swing.JLabel lblCiudadEstadoPaisEmergencia;
    private javax.swing.JLabel lblCorreoEmergencia;
    private javax.swing.JLabel lblDomicilioEmergencia;
    private javax.swing.JLabel lblNombreEmergencia;
    private javax.swing.JLabel lblParentescoEmergencia;
    private javax.swing.JLabel lblTelefonoEmergencia;
    private javax.swing.JLabel lblTituloEmergencia;
    private javax.swing.JTextField txtCelularEmergencia;
    private javax.swing.JTextField txtCiudadEstadoPaisEmergencia;
    private javax.swing.JTextField txtCorreoEmergencia;
    private javax.swing.JTextField txtDomicilioEmergencia;
    private javax.swing.JTextField txtNombreEmergencia;
    private javax.swing.JTextField txtTelefonoEmergencia;
    // End of variables declaration//GEN-END:variables
}
