/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author User
 */
public class pnlDatosSolicitante extends javax.swing.JPanel {

    /**
     * Creates new form pnlDatosSolicitante
     */
    public pnlDatosSolicitante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloSolicitante = new javax.swing.JLabel();
        lblNombreSolicitante = new javax.swing.JLabel();
        lblCarreraSolicitante = new javax.swing.JLabel();
        lblCorreoSolicitante = new javax.swing.JLabel();
        lblSexoSolicitante = new javax.swing.JLabel();
        lblCurpSolicitante = new javax.swing.JLabel();
        txtCurpSolicitante = new javax.swing.JTextField();
        chkSexoMasculino = new javax.swing.JCheckBox();
        chkSexoFemenino = new javax.swing.JCheckBox();
        txtCorreoSolicitante = new javax.swing.JTextField();
        txtCarreraSolicitante = new javax.swing.JTextField();
        txtNombreSolicitante = new javax.swing.JTextField();
        lblLugarResidencia = new javax.swing.JLabel();
        lblTelefonoSolicitante = new javax.swing.JLabel();
        txtTelefonoSolicitante = new javax.swing.JTextField();
        cmbCodigoPaisCelSolicitante = new javax.swing.JComboBox<>();
        lblCelularSolicitante = new javax.swing.JLabel();
        txtLugarResidencia = new javax.swing.JTextField();
        txtCelularSolicitante = new javax.swing.JTextField();
        lblDomicilioSolicitante = new javax.swing.JLabel();
        lblNssSolicitante = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblSemestreSolicitante = new javax.swing.JLabel();
        lblIdAcademico = new javax.swing.JLabel();
        txtIdAcademico = new javax.swing.JTextField();
        cmbSemestreSolicitante = new javax.swing.JComboBox<>();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtNssSolicitante = new javax.swing.JTextField();
        txtDomicilioSolicitante = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lblCorreoInstitucional = new javax.swing.JLabel();
        txtCorreoInstitucional = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloSolicitante.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloSolicitante.setText("Datos del Solicitante");
        jPanel1.add(lblTituloSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        lblNombreSolicitante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblNombreSolicitante.setText("Nombre completo:");
        jPanel1.add(lblNombreSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        lblCarreraSolicitante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCarreraSolicitante.setText("Carrera:");
        jPanel1.add(lblCarreraSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 480, -1, -1));

        lblCorreoSolicitante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCorreoSolicitante.setText("Correo:");
        jPanel1.add(lblCorreoSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, -1));

        lblSexoSolicitante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblSexoSolicitante.setText("Sexo:");
        jPanel1.add(lblSexoSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 140, -1, -1));

        lblCurpSolicitante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCurpSolicitante.setText("CURP:");
        jPanel1.add(lblCurpSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        txtCurpSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCurpSolicitanteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCurpSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 333, 31));

        chkSexoMasculino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkSexoMasculino.setText("Masculino");
        chkSexoMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSexoMasculinoActionPerformed(evt);
            }
        });
        jPanel1.add(chkSexoMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 140, 120, 30));

        chkSexoFemenino.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkSexoFemenino.setText("Femenino");
        jPanel1.add(chkSexoFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, 110, 30));
        jPanel1.add(txtCorreoSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 380, 30));

        txtCarreraSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarreraSolicitanteActionPerformed(evt);
            }
        });
        jPanel1.add(txtCarreraSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 480, 333, 30));

        txtNombreSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreSolicitanteActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 410, 30));

        lblLugarResidencia.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblLugarResidencia.setText("Ciudad, Estado y País de residencia:");
        jPanel1.add(lblLugarResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        lblTelefonoSolicitante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTelefonoSolicitante.setText("Telefono:");
        jPanel1.add(lblTelefonoSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, -1, -1));
        jPanel1.add(txtTelefonoSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 290, 180, 30));

        cmbCodigoPaisCelSolicitante.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbCodigoPaisCelSolicitante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+52", "+67", "+55", "+30", "+33", "+48" }));
        jPanel1.add(cmbCodigoPaisCelSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, -1, 30));

        lblCelularSolicitante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCelularSolicitante.setText("Celular:");
        jPanel1.add(lblCelularSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));
        jPanel1.add(txtLugarResidencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 240, 330, 30));

        txtCelularSolicitante.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelularSolicitanteFocusLost(evt);
            }
        });
        jPanel1.add(txtCelularSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 290, 180, 30));

        lblDomicilioSolicitante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDomicilioSolicitante.setText("Domicilio:");
        jPanel1.add(lblDomicilioSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        lblNssSolicitante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblNssSolicitante.setText("Numero de afiliacion IMSS: ");
        jPanel1.add(lblNssSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblFechaNacimiento.setText("Fecha nacimiento:");
        jPanel1.add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        lblSemestreSolicitante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblSemestreSolicitante.setText("Semestre:");
        jPanel1.add(lblSemestreSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, -1, -1));

        lblIdAcademico.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblIdAcademico.setText("ID:");
        jPanel1.add(lblIdAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, -1, -1));

        txtIdAcademico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAcademicoActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdAcademico, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 170, 30));

        cmbSemestreSolicitante.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbSemestreSolicitante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona semestre en curso", "Semestre 0", "Semestre 1", "Semestre 2", "Semestre 3", "Semestre 4", "Semestre 5", "Semestre 6", "Semestre 7", "Semestre 8", "Semestre 9", "Semestre 10" }));
        jPanel1.add(cmbSemestreSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, 269, 33));

        txtFechaNacimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaNacimientoActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 269, 30));
        jPanel1.add(txtNssSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, 220, 30));

        txtDomicilioSolicitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomicilioSolicitanteActionPerformed(evt);
            }
        });
        jPanel1.add(txtDomicilioSolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 354, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 1120, 10));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 153));
        jLabel2.setText("Datos personales");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 1120, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Datos academicos");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        lblCorreoInstitucional.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCorreoInstitucional.setText("Correo institucional:");
        jPanel1.add(lblCorreoInstitucional, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, -1, -1));
        jPanel1.add(txtCorreoInstitucional, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 380, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1253, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCelularSolicitanteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelularSolicitanteFocusLost
//        if (!txtCelularSoli.getText().trim().isEmpty()) {
//            mostrarSeccion(JpnlDatosTutor);
//        }
    }//GEN-LAST:event_txtCelularSolicitanteFocusLost

    private void txtDomicilioSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomicilioSolicitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioSolicitanteActionPerformed

    private void txtCarreraSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarreraSolicitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarreraSolicitanteActionPerformed

    private void txtNombreSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreSolicitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreSolicitanteActionPerformed

    private void txtCurpSolicitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCurpSolicitanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCurpSolicitanteActionPerformed

    private void txtIdAcademicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAcademicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAcademicoActionPerformed

    private void chkSexoMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSexoMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkSexoMasculinoActionPerformed

    private void txtFechaNacimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaNacimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaNacimientoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkSexoFemenino;
    private javax.swing.JCheckBox chkSexoMasculino;
    private javax.swing.JComboBox<String> cmbCodigoPaisCelSolicitante;
    private javax.swing.JComboBox<String> cmbSemestreSolicitante;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCarreraSolicitante;
    private javax.swing.JLabel lblCelularSolicitante;
    private javax.swing.JLabel lblCorreoInstitucional;
    private javax.swing.JLabel lblCorreoSolicitante;
    private javax.swing.JLabel lblCurpSolicitante;
    private javax.swing.JLabel lblDomicilioSolicitante;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblIdAcademico;
    private javax.swing.JLabel lblLugarResidencia;
    private javax.swing.JLabel lblNombreSolicitante;
    private javax.swing.JLabel lblNssSolicitante;
    private javax.swing.JLabel lblSemestreSolicitante;
    private javax.swing.JLabel lblSexoSolicitante;
    private javax.swing.JLabel lblTelefonoSolicitante;
    private javax.swing.JLabel lblTituloSolicitante;
    private javax.swing.JTextField txtCarreraSolicitante;
    private javax.swing.JTextField txtCelularSolicitante;
    private javax.swing.JTextField txtCorreoInstitucional;
    private javax.swing.JTextField txtCorreoSolicitante;
    private javax.swing.JTextField txtCurpSolicitante;
    private javax.swing.JTextField txtDomicilioSolicitante;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtIdAcademico;
    private javax.swing.JTextField txtLugarResidencia;
    private javax.swing.JTextField txtNombreSolicitante;
    private javax.swing.JTextField txtNssSolicitante;
    private javax.swing.JTextField txtTelefonoSolicitante;
    // End of variables declaration//GEN-END:variables
}
