/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author User
 */
public class pnlDatosMedicos extends javax.swing.JPanel {

    /**
     * Creates new form pnlDatosMedicos
     */
    public pnlDatosMedicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lblTituloDatosMedicos = new javax.swing.JLabel();
        lblEstadoSalud = new javax.swing.JLabel();
        chkSaludBueno = new javax.swing.JCheckBox();
        chkSaludRegular = new javax.swing.JCheckBox();
        chkSaludMalo = new javax.swing.JCheckBox();
        txtEspecificarVista = new javax.swing.JTextField();
        chkVistaNo = new javax.swing.JCheckBox();
        chkVistaSi = new javax.swing.JCheckBox();
        lblDeficienciaVista = new javax.swing.JLabel();
        lblDeficienciaAuditiva = new javax.swing.JLabel();
        chkAuditivaSi = new javax.swing.JCheckBox();
        chkAuditivaNo = new javax.swing.JCheckBox();
        txtEspecificarAuditiva = new javax.swing.JTextField();
        lblDiscapacidadFisica = new javax.swing.JLabel();
        chkFisicaSi = new javax.swing.JCheckBox();
        chkFisicaNo = new javax.swing.JCheckBox();
        txtEspecificarFisica = new javax.swing.JTextField();
        lblLesionesGraves = new javax.swing.JLabel();
        chkLesionesSi = new javax.swing.JCheckBox();
        chkLesionesNo = new javax.swing.JCheckBox();
        txtEspecificarLesiones = new javax.swing.JTextField();
        lblPadecimientos = new javax.swing.JLabel();
        chkPadecimientosSi = new javax.swing.JCheckBox();
        chkPadecimientosNo = new javax.swing.JCheckBox();
        txtEspecificarPadecimientos = new javax.swing.JTextField();
        lblTratamientosPsicologicos = new javax.swing.JLabel();
        lblTratamientosPsicologicos2 = new javax.swing.JLabel();
        chkTratamientosSi = new javax.swing.JCheckBox();
        chkTratamientosNo = new javax.swing.JCheckBox();
        txtMotivoTratamientos = new javax.swing.JTextField();
        lblMedicamentos = new javax.swing.JLabel();
        chkMedicamentosSi = new javax.swing.JCheckBox();
        chkMedicamentosNo = new javax.swing.JCheckBox();
        txtEspecificarMedicamentos = new javax.swing.JTextField();
        lblAlergias = new javax.swing.JLabel();
        chkAlergiasSi = new javax.swing.JCheckBox();
        chkAlergiasNo = new javax.swing.JCheckBox();
        txtEspecificarAlergias = new javax.swing.JTextField();
        lblTratamientosExternos = new javax.swing.JLabel();
        chkExternosSi = new javax.swing.JCheckBox();
        chkExternosNo = new javax.swing.JCheckBox();
        txtMotivoExternos = new javax.swing.JTextField();
        lblTipoSangre = new javax.swing.JLabel();
        cmbTipoSangre = new javax.swing.JComboBox<>();
        lblAspectosSalud = new javax.swing.JLabel();
        lblAspectosSalud2 = new javax.swing.JLabel();
        txaOtraInformacionSalud = new javax.swing.JTextField();
        lblOtraInformacionSalud = new javax.swing.JLabel();
        txtAspectosSalud = new javax.swing.JTextField();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloDatosMedicos.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloDatosMedicos.setText("Datos médicos");
        jPanel2.add(lblTituloDatosMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        lblEstadoSalud.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEstadoSalud.setText("Estado de salud general:");
        jPanel2.add(lblEstadoSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        chkSaludBueno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkSaludBueno.setText("Bueno");
        jPanel2.add(chkSaludBueno, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        chkSaludRegular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkSaludRegular.setText("Regular");
        jPanel2.add(chkSaludRegular, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, -1, -1));

        chkSaludMalo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkSaludMalo.setText("Malo");
        jPanel2.add(chkSaludMalo, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, -1, -1));

        txtEspecificarVista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarVista.setText("especificar");
        jPanel2.add(txtEspecificarVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 230, 30));

        chkVistaNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkVistaNo.setText("NO");
        jPanel2.add(chkVistaNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 180, -1, -1));

        chkVistaSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkVistaSi.setText("SI");
        jPanel2.add(chkVistaSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 180, -1, -1));

        lblDeficienciaVista.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDeficienciaVista.setText("Deficiencia en la vista");
        jPanel2.add(lblDeficienciaVista, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, -1));

        lblDeficienciaAuditiva.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDeficienciaAuditiva.setText("Deficiencia auditiva");
        jPanel2.add(lblDeficienciaAuditiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        chkAuditivaSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAuditivaSi.setText("SI");
        jPanel2.add(chkAuditivaSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, -1, -1));

        chkAuditivaNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAuditivaNo.setText("NO");
        jPanel2.add(chkAuditivaNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, -1, -1));

        txtEspecificarAuditiva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarAuditiva.setText("especificar");
        jPanel2.add(txtEspecificarAuditiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 230, 230, 30));

        lblDiscapacidadFisica.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDiscapacidadFisica.setText("Discapacidad física");
        jPanel2.add(lblDiscapacidadFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        chkFisicaSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkFisicaSi.setText("SI");
        jPanel2.add(chkFisicaSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, -1, -1));

        chkFisicaNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkFisicaNo.setText("NO");
        jPanel2.add(chkFisicaNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 280, -1, -1));

        txtEspecificarFisica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarFisica.setText("especificar");
        jPanel2.add(txtEspecificarFisica, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 230, 30));

        lblLesionesGraves.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblLesionesGraves.setText("Lesiones graves");
        jPanel2.add(lblLesionesGraves, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        chkLesionesSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkLesionesSi.setText("SI");
        jPanel2.add(chkLesionesSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, -1, -1));

        chkLesionesNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkLesionesNo.setText("NO");
        jPanel2.add(chkLesionesNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 330, -1, -1));

        txtEspecificarLesiones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarLesiones.setText("especificar");
        jPanel2.add(txtEspecificarLesiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 330, 230, 30));

        lblPadecimientos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblPadecimientos.setText("Padecimientos actuales o previos");
        jPanel2.add(lblPadecimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        chkPadecimientosSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkPadecimientosSi.setText("SI");
        jPanel2.add(chkPadecimientosSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        chkPadecimientosNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkPadecimientosNo.setText("NO");
        jPanel2.add(chkPadecimientosNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 370, -1, -1));

        txtEspecificarPadecimientos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarPadecimientos.setText("especificar");
        jPanel2.add(txtEspecificarPadecimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 230, 30));

        lblTratamientosPsicologicos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTratamientosPsicologicos.setText("Tratamientos médicos, psiquiátricos ");
        jPanel2.add(lblTratamientosPsicologicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        lblTratamientosPsicologicos2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTratamientosPsicologicos2.setText("o psicológicos");
        jPanel2.add(lblTratamientosPsicologicos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, -1, -1));

        chkTratamientosSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkTratamientosSi.setText("SI");
        jPanel2.add(chkTratamientosSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, -1, -1));

        chkTratamientosNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkTratamientosNo.setText("NO");
        jPanel2.add(chkTratamientosNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, -1, -1));

        txtMotivoTratamientos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMotivoTratamientos.setText("Motivo o pronostico");
        jPanel2.add(txtMotivoTratamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 430, 230, 30));

        lblMedicamentos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblMedicamentos.setText("Medicamentos controlados");
        jPanel2.add(lblMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, -1, -1));

        chkMedicamentosSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkMedicamentosSi.setText("SI");
        jPanel2.add(chkMedicamentosSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, -1, -1));

        chkMedicamentosNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkMedicamentosNo.setText("NO");
        jPanel2.add(chkMedicamentosNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 480, -1, -1));

        txtEspecificarMedicamentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarMedicamentos.setText("especificar");
        jPanel2.add(txtEspecificarMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 480, 230, 30));

        lblAlergias.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblAlergias.setText("Alergias");
        jPanel2.add(lblAlergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, -1, -1));

        chkAlergiasSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAlergiasSi.setText("SI");
        jPanel2.add(chkAlergiasSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 520, -1, -1));

        chkAlergiasNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAlergiasNo.setText("NO");
        jPanel2.add(chkAlergiasNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 520, -1, -1));

        txtEspecificarAlergias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarAlergias.setText("especificar");
        jPanel2.add(txtEspecificarAlergias, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 520, 230, 30));

        lblTratamientosExternos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTratamientosExternos.setText("Tratamientos externos");
        jPanel2.add(lblTratamientosExternos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, -1, -1));

        chkExternosSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkExternosSi.setText("SI");
        jPanel2.add(chkExternosSi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, -1, -1));

        chkExternosNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkExternosNo.setText("NO");
        jPanel2.add(chkExternosNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, -1, -1));

        txtMotivoExternos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMotivoExternos.setText("Motivo");
        jPanel2.add(txtMotivoExternos, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 570, 230, 30));

        lblTipoSangre.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTipoSangre.setText("Tipo de sangre");
        jPanel2.add(lblTipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 630, -1, -1));

        cmbTipoSangre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbTipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un tipo de sangre", "A+", "B+", "O-", "O+", "A-", "B-", "X" }));
        jPanel2.add(cmbTipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 640, 290, 30));

        lblAspectosSalud.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblAspectosSalud.setText("Aspectos de salud en los que te gustaría");
        jPanel2.add(lblAspectosSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 670, -1, -1));

        lblAspectosSalud2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblAspectosSalud2.setText("prepararte mejor");
        jPanel2.add(lblAspectosSalud2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 700, -1, -1));

        txaOtraInformacionSalud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txaOtraInformacionSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 740, 410, 60));

        lblOtraInformacionSalud.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblOtraInformacionSalud.setText("Otra información importante sobre tu salud");
        jPanel2.add(lblOtraInformacionSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 740, -1, -1));

        txtAspectosSalud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(txtAspectosSalud, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 680, 410, 30));

        jScrollPane1.setViewportView(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1260, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAlergiasNo;
    private javax.swing.JCheckBox chkAlergiasSi;
    private javax.swing.JCheckBox chkAuditivaNo;
    private javax.swing.JCheckBox chkAuditivaSi;
    private javax.swing.JCheckBox chkExternosNo;
    private javax.swing.JCheckBox chkExternosSi;
    private javax.swing.JCheckBox chkFisicaNo;
    private javax.swing.JCheckBox chkFisicaSi;
    private javax.swing.JCheckBox chkLesionesNo;
    private javax.swing.JCheckBox chkLesionesSi;
    private javax.swing.JCheckBox chkMedicamentosNo;
    private javax.swing.JCheckBox chkMedicamentosSi;
    private javax.swing.JCheckBox chkPadecimientosNo;
    private javax.swing.JCheckBox chkPadecimientosSi;
    private javax.swing.JCheckBox chkSaludBueno;
    private javax.swing.JCheckBox chkSaludMalo;
    private javax.swing.JCheckBox chkSaludRegular;
    private javax.swing.JCheckBox chkTratamientosNo;
    private javax.swing.JCheckBox chkTratamientosSi;
    private javax.swing.JCheckBox chkVistaNo;
    private javax.swing.JCheckBox chkVistaSi;
    private javax.swing.JComboBox<String> cmbTipoSangre;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlergias;
    private javax.swing.JLabel lblAspectosSalud;
    private javax.swing.JLabel lblAspectosSalud2;
    private javax.swing.JLabel lblDeficienciaAuditiva;
    private javax.swing.JLabel lblDeficienciaVista;
    private javax.swing.JLabel lblDiscapacidadFisica;
    private javax.swing.JLabel lblEstadoSalud;
    private javax.swing.JLabel lblLesionesGraves;
    private javax.swing.JLabel lblMedicamentos;
    private javax.swing.JLabel lblOtraInformacionSalud;
    private javax.swing.JLabel lblPadecimientos;
    private javax.swing.JLabel lblTipoSangre;
    private javax.swing.JLabel lblTituloDatosMedicos;
    private javax.swing.JLabel lblTratamientosExternos;
    private javax.swing.JLabel lblTratamientosPsicologicos;
    private javax.swing.JLabel lblTratamientosPsicologicos2;
    private javax.swing.JTextField txaOtraInformacionSalud;
    private javax.swing.JTextField txtAspectosSalud;
    private javax.swing.JTextField txtEspecificarAlergias;
    private javax.swing.JTextField txtEspecificarAuditiva;
    private javax.swing.JTextField txtEspecificarFisica;
    private javax.swing.JTextField txtEspecificarLesiones;
    private javax.swing.JTextField txtEspecificarMedicamentos;
    private javax.swing.JTextField txtEspecificarPadecimientos;
    private javax.swing.JTextField txtEspecificarVista;
    private javax.swing.JTextField txtMotivoExternos;
    private javax.swing.JTextField txtMotivoTratamientos;
    // End of variables declaration//GEN-END:variables
}
