/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author User
 */
public class pnlDatosMedicos extends javax.swing.JPanel {

    /**
     * Creates new form pnlDatosMedicos
     */
    public pnlDatosMedicos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblTituloDatosMedicos = new javax.swing.JLabel();
        lblEstadoSalud = new javax.swing.JLabel();
        chkSaludBueno = new javax.swing.JCheckBox();
        chkSaludRegular = new javax.swing.JCheckBox();
        chkSaludMalo = new javax.swing.JCheckBox();
        txtEspecificarVista = new javax.swing.JTextField();
        chkVistaNo = new javax.swing.JCheckBox();
        chkVistaSi = new javax.swing.JCheckBox();
        lblDeficienciaVista = new javax.swing.JLabel();
        lblDeficienciaAuditiva = new javax.swing.JLabel();
        chkAuditivaSi = new javax.swing.JCheckBox();
        chkAuditivaNo = new javax.swing.JCheckBox();
        txtEspecificarAuditiva = new javax.swing.JTextField();
        lblDiscapacidadFisica = new javax.swing.JLabel();
        chkFisicaSi = new javax.swing.JCheckBox();
        chkFisicaNo = new javax.swing.JCheckBox();
        txtEspecificarFisica = new javax.swing.JTextField();
        lblLesionesGraves = new javax.swing.JLabel();
        chkLesionesSi = new javax.swing.JCheckBox();
        chkLesionesNo = new javax.swing.JCheckBox();
        txtEspecificarLesiones = new javax.swing.JTextField();
        lblPadecimientos = new javax.swing.JLabel();
        chkPadecimientosSi = new javax.swing.JCheckBox();
        chkPadecimientosNo = new javax.swing.JCheckBox();
        txtEspecificarPadecimientos = new javax.swing.JTextField();
        lblTratamientosPsicologicos = new javax.swing.JLabel();
        lblTratamientosPsicologicos2 = new javax.swing.JLabel();
        chkTratamientosSi = new javax.swing.JCheckBox();
        chkTratamientosNo = new javax.swing.JCheckBox();
        txtMotivoTratamientos = new javax.swing.JTextField();
        lblMedicamentos = new javax.swing.JLabel();
        chkMedicamentosSi = new javax.swing.JCheckBox();
        chkMedicamentosNo = new javax.swing.JCheckBox();
        txtEspecificarMedicamentos = new javax.swing.JTextField();
        lblAlergias = new javax.swing.JLabel();
        chkAlergiasSi = new javax.swing.JCheckBox();
        chkAlergiasNo = new javax.swing.JCheckBox();
        txtEspecificarAlergias = new javax.swing.JTextField();
        lblTratamientosExternos = new javax.swing.JLabel();
        chkExternosSi = new javax.swing.JCheckBox();
        chkExternosNo = new javax.swing.JCheckBox();
        txtMotivoExternos = new javax.swing.JTextField();
        lblTipoSangre = new javax.swing.JLabel();
        cmbTipoSangre = new javax.swing.JComboBox<>();
        lblAspectosSalud = new javax.swing.JLabel();
        lblAspectosSalud2 = new javax.swing.JLabel();
        lblOtraInformacionSalud = new javax.swing.JLabel();
        txtAspectosSalud = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaOtraInformacionSalud = new javax.swing.JTextArea();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloDatosMedicos.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloDatosMedicos.setText("Datos médicos");

        lblEstadoSalud.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEstadoSalud.setText("Estado de salud general:");

        chkSaludBueno.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkSaludBueno.setText("Bueno");

        chkSaludRegular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkSaludRegular.setText("Regular");

        chkSaludMalo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkSaludMalo.setText("Malo");

        txtEspecificarVista.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarVista.setText("especificar");

        chkVistaNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkVistaNo.setText("NO");

        chkVistaSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkVistaSi.setText("SI");

        lblDeficienciaVista.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDeficienciaVista.setText("Deficiencia en la vista");

        lblDeficienciaAuditiva.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDeficienciaAuditiva.setText("Deficiencia auditiva");

        chkAuditivaSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAuditivaSi.setText("SI");

        chkAuditivaNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAuditivaNo.setText("NO");

        txtEspecificarAuditiva.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarAuditiva.setText("especificar");

        lblDiscapacidadFisica.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDiscapacidadFisica.setText("Discapacidad física");

        chkFisicaSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkFisicaSi.setText("SI");

        chkFisicaNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkFisicaNo.setText("NO");

        txtEspecificarFisica.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarFisica.setText("especificar");

        lblLesionesGraves.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblLesionesGraves.setText("Lesiones graves");

        chkLesionesSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkLesionesSi.setText("SI");

        chkLesionesNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkLesionesNo.setText("NO");

        txtEspecificarLesiones.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarLesiones.setText("especificar");

        lblPadecimientos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblPadecimientos.setText("Padecimientos actuales o previos");

        chkPadecimientosSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkPadecimientosSi.setText("SI");

        chkPadecimientosNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkPadecimientosNo.setText("NO");

        txtEspecificarPadecimientos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarPadecimientos.setText("especificar");

        lblTratamientosPsicologicos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTratamientosPsicologicos.setText("Tratamientos médicos, psiquiátricos ");

        lblTratamientosPsicologicos2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTratamientosPsicologicos2.setText("o psicológicos");

        chkTratamientosSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkTratamientosSi.setText("SI");

        chkTratamientosNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkTratamientosNo.setText("NO");

        txtMotivoTratamientos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMotivoTratamientos.setText("Motivo o pronostico");

        lblMedicamentos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblMedicamentos.setText("Medicamentos controlados");

        chkMedicamentosSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkMedicamentosSi.setText("SI");

        chkMedicamentosNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkMedicamentosNo.setText("NO");

        txtEspecificarMedicamentos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarMedicamentos.setText("especificar");

        lblAlergias.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblAlergias.setText("Alergias");

        chkAlergiasSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAlergiasSi.setText("SI");

        chkAlergiasNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkAlergiasNo.setText("NO");

        txtEspecificarAlergias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtEspecificarAlergias.setText("especificar");

        lblTratamientosExternos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTratamientosExternos.setText("Tratamientos externos");

        chkExternosSi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkExternosSi.setText("SI");

        chkExternosNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkExternosNo.setText("NO");

        txtMotivoExternos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMotivoExternos.setText("Motivo");

        lblTipoSangre.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTipoSangre.setText("Tipo de sangre");

        cmbTipoSangre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbTipoSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un tipo de sangre", "A+", "B+", "O-", "O+", "A-", "B-", "X" }));

        lblAspectosSalud.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblAspectosSalud.setText("Aspectos de salud en los que te gustaría");

        lblAspectosSalud2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblAspectosSalud2.setText("prepararte mejor");

        lblOtraInformacionSalud.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblOtraInformacionSalud.setText("Otra información importante sobre tu salud");

        txtAspectosSalud.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txaOtraInformacionSalud.setColumns(20);
        txaOtraInformacionSalud.setRows(5);
        jScrollPane1.setViewportView(txaOtraInformacionSalud);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAspectosSalud2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAspectosSalud)
                            .addComponent(lblOtraInformacionSalud))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAspectosSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblTituloDatosMedicos))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblEstadoSalud)
                        .addGap(183, 183, 183)
                        .addComponent(chkSaludBueno)
                        .addGap(66, 66, 66)
                        .addComponent(chkSaludRegular)
                        .addGap(64, 64, 64)
                        .addComponent(chkSaludMalo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblDeficienciaVista)
                        .addGap(210, 210, 210)
                        .addComponent(chkVistaSi)
                        .addGap(103, 103, 103)
                        .addComponent(chkVistaNo)
                        .addGap(100, 100, 100)
                        .addComponent(txtEspecificarVista, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblDeficienciaAuditiva)
                        .addGap(228, 228, 228)
                        .addComponent(chkAuditivaSi)
                        .addGap(103, 103, 103)
                        .addComponent(chkAuditivaNo)
                        .addGap(100, 100, 100)
                        .addComponent(txtEspecificarAuditiva, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblDiscapacidadFisica)
                        .addGap(230, 230, 230)
                        .addComponent(chkFisicaSi)
                        .addGap(103, 103, 103)
                        .addComponent(chkFisicaNo)
                        .addGap(100, 100, 100)
                        .addComponent(txtEspecificarFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblLesionesGraves)
                        .addGap(260, 260, 260)
                        .addComponent(chkLesionesSi)
                        .addGap(103, 103, 103)
                        .addComponent(chkLesionesNo)
                        .addGap(100, 100, 100)
                        .addComponent(txtEspecificarLesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblPadecimientos)
                        .addGap(105, 105, 105)
                        .addComponent(chkPadecimientosSi)
                        .addGap(103, 103, 103)
                        .addComponent(chkPadecimientosNo)
                        .addGap(100, 100, 100)
                        .addComponent(txtEspecificarPadecimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTratamientosPsicologicos2)
                            .addComponent(lblTratamientosPsicologicos))
                        .addGap(75, 75, 75)
                        .addComponent(chkTratamientosSi)
                        .addGap(103, 103, 103)
                        .addComponent(chkTratamientosNo)
                        .addGap(100, 100, 100)
                        .addComponent(txtMotivoTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblMedicamentos)
                        .addGap(157, 157, 157)
                        .addComponent(chkMedicamentosSi)
                        .addGap(103, 103, 103)
                        .addComponent(chkMedicamentosNo)
                        .addGap(100, 100, 100)
                        .addComponent(txtEspecificarMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblAlergias)
                        .addGap(329, 329, 329)
                        .addComponent(chkAlergiasSi)
                        .addGap(103, 103, 103)
                        .addComponent(chkAlergiasNo)
                        .addGap(100, 100, 100)
                        .addComponent(txtEspecificarAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTratamientosExternos)
                            .addComponent(lblTipoSangre))
                        .addGap(203, 203, 203)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(chkExternosSi)
                                .addGap(103, 103, 103)
                                .addComponent(chkExternosNo)
                                .addGap(100, 100, 100)
                                .addComponent(txtMotivoExternos, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(98, 98, 98))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloDatosMedicos)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadoSalud)
                    .addComponent(chkSaludBueno)
                    .addComponent(chkSaludRegular)
                    .addComponent(chkSaludMalo))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeficienciaVista)
                    .addComponent(chkVistaSi)
                    .addComponent(chkVistaNo)
                    .addComponent(txtEspecificarVista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeficienciaAuditiva)
                    .addComponent(chkAuditivaSi)
                    .addComponent(chkAuditivaNo)
                    .addComponent(txtEspecificarAuditiva, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiscapacidadFisica)
                    .addComponent(chkFisicaSi)
                    .addComponent(chkFisicaNo)
                    .addComponent(txtEspecificarFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLesionesGraves)
                    .addComponent(chkLesionesSi)
                    .addComponent(chkLesionesNo)
                    .addComponent(txtEspecificarLesiones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPadecimientos)
                    .addComponent(chkPadecimientosSi)
                    .addComponent(chkPadecimientosNo)
                    .addComponent(txtEspecificarPadecimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTratamientosPsicologicos)
                            .addComponent(chkTratamientosSi)
                            .addComponent(chkTratamientosNo)
                            .addComponent(txtMotivoTratamientos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTratamientosPsicologicos2)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMedicamentos)
                    .addComponent(chkMedicamentosSi)
                    .addComponent(chkMedicamentosNo)
                    .addComponent(txtEspecificarMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlergias)
                    .addComponent(chkAlergiasSi)
                    .addComponent(chkAlergiasNo)
                    .addComponent(txtEspecificarAlergias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTratamientosExternos)
                    .addComponent(chkExternosSi)
                    .addComponent(chkExternosNo)
                    .addComponent(txtMotivoExternos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoSangre)
                    .addComponent(cmbTipoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAspectosSalud)
                    .addComponent(txtAspectosSalud, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(lblAspectosSalud2)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblOtraInformacionSalud)
                        .addContainerGap(67, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAlergiasNo;
    private javax.swing.JCheckBox chkAlergiasSi;
    private javax.swing.JCheckBox chkAuditivaNo;
    private javax.swing.JCheckBox chkAuditivaSi;
    private javax.swing.JCheckBox chkExternosNo;
    private javax.swing.JCheckBox chkExternosSi;
    private javax.swing.JCheckBox chkFisicaNo;
    private javax.swing.JCheckBox chkFisicaSi;
    private javax.swing.JCheckBox chkLesionesNo;
    private javax.swing.JCheckBox chkLesionesSi;
    private javax.swing.JCheckBox chkMedicamentosNo;
    private javax.swing.JCheckBox chkMedicamentosSi;
    private javax.swing.JCheckBox chkPadecimientosNo;
    private javax.swing.JCheckBox chkPadecimientosSi;
    private javax.swing.JCheckBox chkSaludBueno;
    private javax.swing.JCheckBox chkSaludMalo;
    private javax.swing.JCheckBox chkSaludRegular;
    private javax.swing.JCheckBox chkTratamientosNo;
    private javax.swing.JCheckBox chkTratamientosSi;
    private javax.swing.JCheckBox chkVistaNo;
    private javax.swing.JCheckBox chkVistaSi;
    private javax.swing.JComboBox<String> cmbTipoSangre;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAlergias;
    private javax.swing.JLabel lblAspectosSalud;
    private javax.swing.JLabel lblAspectosSalud2;
    private javax.swing.JLabel lblDeficienciaAuditiva;
    private javax.swing.JLabel lblDeficienciaVista;
    private javax.swing.JLabel lblDiscapacidadFisica;
    private javax.swing.JLabel lblEstadoSalud;
    private javax.swing.JLabel lblLesionesGraves;
    private javax.swing.JLabel lblMedicamentos;
    private javax.swing.JLabel lblOtraInformacionSalud;
    private javax.swing.JLabel lblPadecimientos;
    private javax.swing.JLabel lblTipoSangre;
    private javax.swing.JLabel lblTituloDatosMedicos;
    private javax.swing.JLabel lblTratamientosExternos;
    private javax.swing.JLabel lblTratamientosPsicologicos;
    private javax.swing.JLabel lblTratamientosPsicologicos2;
    private javax.swing.JTextArea txaOtraInformacionSalud;
    private javax.swing.JTextField txtAspectosSalud;
    private javax.swing.JTextField txtEspecificarAlergias;
    private javax.swing.JTextField txtEspecificarAuditiva;
    private javax.swing.JTextField txtEspecificarFisica;
    private javax.swing.JTextField txtEspecificarLesiones;
    private javax.swing.JTextField txtEspecificarMedicamentos;
    private javax.swing.JTextField txtEspecificarPadecimientos;
    private javax.swing.JTextField txtEspecificarVista;
    private javax.swing.JTextField txtMotivoExternos;
    private javax.swing.JTextField txtMotivoTratamientos;
    // End of variables declaration//GEN-END:variables
}
