/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author User
 */
public class pnlDatosTutor extends javax.swing.JPanel {

    /**
     * Creates new form pnlDatosTutor
     */
    public pnlDatosTutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEmailsolicitante = new javax.swing.JLabel();
        txtEmailSoli = new javax.swing.JTextField();
        txtNombreTutor = new javax.swing.JTextField();
        lblCiudadSoli = new javax.swing.JLabel();
        lblTelefonoSOli = new javax.swing.JLabel();
        txtTelefonoSoli = new javax.swing.JTextField();
        txtExtensionCelularSoli = new javax.swing.JComboBox<>();
        lblCelularSoli = new javax.swing.JLabel();
        txtXiudadSoli = new javax.swing.JTextField();
        txtCelularSoli = new javax.swing.JTextField();
        lblDomsoli = new javax.swing.JLabel();
        txtDomicilioSoli = new javax.swing.JTextField();
        lblParentesco = new javax.swing.JLabel();
        cmbxParentescoEmerg = new javax.swing.JComboBox<>();
        lblNombreTutor = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        jLabel1.setText("Datos del Tutor");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));

        lblEmailsolicitante.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEmailsolicitante.setText("Correo:");
        jPanel1.add(lblEmailsolicitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));
        jPanel1.add(txtEmailSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 380, 30));

        txtNombreTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTutorActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 400, 30));

        lblCiudadSoli.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCiudadSoli.setText("Ciudad, Estado y País de residencia:");
        jPanel1.add(lblCiudadSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, -1, -1));

        lblTelefonoSOli.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTelefonoSOli.setText("Telefono:");
        jPanel1.add(lblTelefonoSOli, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 240, -1, -1));
        jPanel1.add(txtTelefonoSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 180, 30));

        txtExtensionCelularSoli.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+52", "+67", "+55", "+30", "+33", "+48" }));
        jPanel1.add(txtExtensionCelularSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, -1, 30));

        lblCelularSoli.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCelularSoli.setText("Celular:");
        jPanel1.add(lblCelularSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));
        jPanel1.add(txtXiudadSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 300, 30));

        txtCelularSoli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelularSoliFocusLost(evt);
            }
        });
        jPanel1.add(txtCelularSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 180, 30));

        lblDomsoli.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDomsoli.setText("Domicilio:");
        jPanel1.add(lblDomsoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, -1, -1));

        txtDomicilioSoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomicilioSoliActionPerformed(evt);
            }
        });
        jPanel1.add(txtDomicilioSoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 354, 30));

        lblParentesco.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblParentesco.setText("Parentesco:");
        jPanel1.add(lblParentesco, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, -1, -1));

        cmbxParentescoEmerg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un parentesco", "Padre", "Madre", "Hermano", "Abuela/Abuelo", "Tutor legal" }));
        jPanel1.add(cmbxParentescoEmerg, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 140, -1, 30));

        lblNombreTutor.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblNombreTutor.setText("Nombre completo:");
        jPanel1.add(lblNombreTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1253, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTutorActionPerformed

    private void txtCelularSoliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelularSoliFocusLost
        //        if (!txtCelularSoli.getText().trim().isEmpty()) {
            //            mostrarSeccion(JpnlDatosTutor);
            //        }
    }//GEN-LAST:event_txtCelularSoliFocusLost

    private void txtDomicilioSoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomicilioSoliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioSoliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbxParentescoEmerg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCelularSoli;
    private javax.swing.JLabel lblCiudadSoli;
    private javax.swing.JLabel lblDomsoli;
    private javax.swing.JLabel lblEmailsolicitante;
    private javax.swing.JLabel lblNombreTutor;
    private javax.swing.JLabel lblParentesco;
    private javax.swing.JLabel lblTelefonoSOli;
    private javax.swing.JTextField txtCelularSoli;
    private javax.swing.JTextField txtDomicilioSoli;
    private javax.swing.JTextField txtEmailSoli;
    private javax.swing.JComboBox<String> txtExtensionCelularSoli;
    private javax.swing.JTextField txtNombreTutor;
    private javax.swing.JTextField txtTelefonoSoli;
    private javax.swing.JTextField txtXiudadSoli;
    // End of variables declaration//GEN-END:variables
}
