/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion;

/**
 *
 * @author User
 */
public class pnlDatosTutor extends javax.swing.JPanel {

    /**
     * Creates new form pnlDatosTutor
     */
    public pnlDatosTutor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloTutor = new javax.swing.JLabel();
        lblCorreoTutor = new javax.swing.JLabel();
        txtCorreoTutor = new javax.swing.JTextField();
        txtNombreTutor = new javax.swing.JTextField();
        lblCiudadEstadoPaisTutor = new javax.swing.JLabel();
        lblTelefonoTutor = new javax.swing.JLabel();
        txtTelefonoTutor = new javax.swing.JTextField();
        cmbCodigoPaisTutor = new javax.swing.JComboBox<>();
        lblCelularTutor = new javax.swing.JLabel();
        txtCiudadEstadoPaisTutor = new javax.swing.JTextField();
        txtCelularTutor = new javax.swing.JTextField();
        lblDomicilioTutor = new javax.swing.JLabel();
        txtDomicilioTutor = new javax.swing.JTextField();
        lblParentescoTutor = new javax.swing.JLabel();
        cmbParentescoTutor = new javax.swing.JComboBox<>();
        lblNombreTutor = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloTutor.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloTutor.setText("Datos del Tutor");

        lblCorreoTutor.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCorreoTutor.setText("Correo:");

        txtNombreTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTutorActionPerformed(evt);
            }
        });

        lblCiudadEstadoPaisTutor.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCiudadEstadoPaisTutor.setText("Ciudad, Estado y País de residencia:");

        lblTelefonoTutor.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblTelefonoTutor.setText("Telefono:");

        cmbCodigoPaisTutor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbCodigoPaisTutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+52", "+67", "+55", "+30", "+33", "+48" }));

        lblCelularTutor.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblCelularTutor.setText("Celular:");

        txtCelularTutor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelularTutorFocusLost(evt);
            }
        });

        lblDomicilioTutor.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblDomicilioTutor.setText("Domicilio:");

        txtDomicilioTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDomicilioTutorActionPerformed(evt);
            }
        });

        lblParentescoTutor.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblParentescoTutor.setText("Parentesco:");

        cmbParentescoTutor.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbParentescoTutor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona un parentesco", "Padre", "Madre", "Hermano", "Abuela/Abuelo", "Tutor legal" }));

        lblNombreTutor.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblNombreTutor.setText("Nombre completo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblTituloTutor))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblNombreTutor)
                .addGap(11, 11, 11)
                .addComponent(txtNombreTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(lblParentescoTutor)
                .addGap(8, 8, 8)
                .addComponent(cmbParentescoTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblDomicilioTutor)
                .addGap(21, 21, 21)
                .addComponent(txtDomicilioTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblCiudadEstadoPaisTutor)
                .addGap(15, 15, 15)
                .addComponent(txtCiudadEstadoPaisTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblCelularTutor)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(txtCelularTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbCodigoPaisTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(lblTelefonoTutor)
                .addGap(28, 28, 28)
                .addComponent(txtTelefonoTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(lblCorreoTutor)
                .addGap(15, 15, 15)
                .addComponent(txtCorreoTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloTutor)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreTutor)
                    .addComponent(txtNombreTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblParentescoTutor)
                    .addComponent(cmbParentescoTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDomicilioTutor)
                    .addComponent(txtDomicilioTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCiudadEstadoPaisTutor)
                    .addComponent(txtCiudadEstadoPaisTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCelularTutor)
                    .addComponent(txtCelularTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCodigoPaisTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefonoTutor)
                    .addComponent(txtTelefonoTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCorreoTutor)
                    .addComponent(txtCorreoTutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTutorActionPerformed

    private void txtCelularTutorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelularTutorFocusLost
        //        if (!txtCelularSoli.getText().trim().isEmpty()) {
            //            mostrarSeccion(JpnlDatosTutor);
            //        }
    }//GEN-LAST:event_txtCelularTutorFocusLost

    private void txtDomicilioTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDomicilioTutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDomicilioTutorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCodigoPaisTutor;
    private javax.swing.JComboBox<String> cmbParentescoTutor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCelularTutor;
    private javax.swing.JLabel lblCiudadEstadoPaisTutor;
    private javax.swing.JLabel lblCorreoTutor;
    private javax.swing.JLabel lblDomicilioTutor;
    private javax.swing.JLabel lblNombreTutor;
    private javax.swing.JLabel lblParentescoTutor;
    private javax.swing.JLabel lblTelefonoTutor;
    private javax.swing.JLabel lblTituloTutor;
    private javax.swing.JTextField txtCelularTutor;
    private javax.swing.JTextField txtCiudadEstadoPaisTutor;
    private javax.swing.JTextField txtCorreoTutor;
    private javax.swing.JTextField txtDomicilioTutor;
    private javax.swing.JTextField txtNombreTutor;
    private javax.swing.JTextField txtTelefonoTutor;
    // End of variables declaration//GEN-END:variables
}
