package Presentacion;

/**
 *
 * @author Valeria
 */
public class pnlFormaPago extends javax.swing.JPanel {

    /**
     * Creates new form pnlFormaPago
     */
    public pnlFormaPago() {
        initComponents();
        agruparCasillas();
        configurarDinamismo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloTutor = new javax.swing.JLabel();
        chkContadoIndividual = new javax.swing.JCheckBox();
        chkCincuentaInicial = new javax.swing.JCheckBox();
        chkCuatroPagosIguales = new javax.swing.JCheckBox();
        chkContadoHermanos = new javax.swing.JCheckBox();
        chkCuatroPagosHermanos = new javax.swing.JCheckBox();
        txtMontoCuatroPagosHermanos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMontoContadoHermanos = new javax.swing.JTextField();
        txtMontoCuatroPagosIguales = new javax.swing.JTextField();
        txtMontoCincuentaInicial = new javax.swing.JTextField();
        txtMontoContadoIndividual = new javax.swing.JTextField();
        lblNotaInformativaPago = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblTituloTutor.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        lblTituloTutor.setText("Forma de pago (seleccionar una opción)");

        chkContadoIndividual.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        chkContadoIndividual.setText("Contado (individual):  $");
        chkContadoIndividual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkContadoIndividualActionPerformed(evt);
            }
        });

        chkCincuentaInicial.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        chkCincuentaInicial.setText("50 % inicial + 3 pagos de:  $");

        chkCuatroPagosIguales.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        chkCuatroPagosIguales.setText(" 4 pagos iguales de: $");

        chkContadoHermanos.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        chkContadoHermanos.setText(" Contado (hermanos) : $");

        chkCuatroPagosHermanos.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        chkCuatroPagosHermanos.setText(" 4 pagos");
        chkCuatroPagosHermanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCuatroPagosHermanosActionPerformed(evt);
            }
        });

        txtMontoCuatroPagosHermanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoCuatroPagosHermanosActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        jLabel3.setText("(hermanos): $");

        lblNotaInformativaPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNotaInformativaPago.setText("Nota informativa: Todo ingreso requiere depósito-garantía (no reembolsable en caso de cancelación).");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(lblTituloTutor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkContadoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(txtMontoContadoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkCuatroPagosIguales, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(txtMontoCuatroPagosIguales, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(chkCuatroPagosHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chkCincuentaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(txtMontoCincuentaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(16, 16, 16)
                                    .addComponent(txtMontoCuatroPagosHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(chkContadoHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(10, 10, 10)
                                    .addComponent(txtMontoContadoHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(lblNotaInformativaPago, javax.swing.GroupLayout.PREFERRED_SIZE, 828, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblTituloTutor)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkContadoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoContadoIndividual, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkCincuentaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoCincuentaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkCuatroPagosIguales, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoCuatroPagosIguales, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkContadoHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMontoContadoHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(chkCuatroPagosHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(txtMontoCuatroPagosHermanos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addComponent(lblNotaInformativaPago)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chkContadoIndividualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkContadoIndividualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkContadoIndividualActionPerformed

    private void chkCuatroPagosHermanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCuatroPagosHermanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCuatroPagosHermanosActionPerformed

    private void txtMontoCuatroPagosHermanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoCuatroPagosHermanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoCuatroPagosHermanosActionPerformed

    private void configurarDinamismo() {
        // Al arrancar, forzamos a que todas se apaguen y digan 0.00
        actualizarCajasPago();

        // Le ponemos un "escuchador" a cada checkbox. Cuando le den clic a cualquiera,
        // se revisan todas las cajas para ver cuál se enciende y cuáles se apagan.
        java.awt.event.ActionListener accionListener = evt -> actualizarCajasPago();

        chkContadoIndividual.addActionListener(accionListener);
        chkCincuentaInicial.addActionListener(accionListener);
        chkCuatroPagosIguales.addActionListener(accionListener);
        chkContadoHermanos.addActionListener(accionListener);
        chkCuatroPagosHermanos.addActionListener(accionListener);
    }

    private void actualizarCajasPago() {
        manejarCaja(chkContadoIndividual, txtMontoContadoIndividual);
        manejarCaja(chkCincuentaInicial, txtMontoCincuentaInicial);
        manejarCaja(chkCuatroPagosIguales, txtMontoCuatroPagosIguales);
        manejarCaja(chkContadoHermanos, txtMontoContadoHermanos);
        manejarCaja(chkCuatroPagosHermanos, txtMontoCuatroPagosHermanos);
    }

    private void manejarCaja(javax.swing.JCheckBox chk, javax.swing.JTextField txt) {
        if (chk.isSelected()) {
            txt.setEnabled(true);
            txt.setForeground(java.awt.Color.BLACK);
            // Si tiene el texto por defecto, lo limpiamos para que el usuario escriba
            if (txt.getText().equals("0.00")) {
                txt.setText("");
            }
            txt.requestFocus(); // Manda el cursor ahí automáticamente
        } else {
            txt.setEnabled(false);
            txt.setText("0.00");
            txt.setForeground(new java.awt.Color(153, 153, 153)); // Color gris
            marcarError(txt, true); // Le quitamos el fondo rosa si estaba marcado como error
        }
    }

    /**
     * Este metodo es llamado desde FrmSolicitudIngreso para que este panel
     * guarde sus datos en el maletín de la Solicitud.
     *
     * @param dtoSol
     */
    public void empaquetarDatosPago(Negocio.DTOs.SolicitudIngresoDTO dtoSol) {

        // Forma de pago (Checkboxes y sus textos)
        if (chkContadoIndividual.isSelected()) {
            dtoSol.setTipoPago("Contado (individual)");
            dtoSol.setMontoPago(txtMontoContadoIndividual.getText().trim());

        } else if (chkCincuentaInicial.isSelected()) {
            dtoSol.setTipoPago("50% inicial + 3 pagos");
            dtoSol.setMontoPago(txtMontoCincuentaInicial.getText().trim());

        } else if (chkCuatroPagosIguales.isSelected()) {
            dtoSol.setTipoPago("4 pagos iguales");
            dtoSol.setMontoPago(txtMontoCuatroPagosIguales.getText().trim());

        } else if (chkContadoHermanos.isSelected()) {
            dtoSol.setTipoPago("Contado (hermanos)");
            dtoSol.setMontoPago(txtMontoContadoHermanos.getText().trim());

        } else if (chkCuatroPagosHermanos.isSelected()) {
            dtoSol.setTipoPago("4 pagos (hermanos)");
            dtoSol.setMontoPago(txtMontoCuatroPagosHermanos.getText().trim());
        } else {
            // Por si el usuario no selecciona nada
            dtoSol.setTipoPago("");
            dtoSol.setMontoPago("");
        }
    }

    //metodos ayudantes de validación
    private boolean campoEsValido(javax.swing.JTextField campo) {
        String texto = campo.getText().trim();
        boolean valido = !texto.isEmpty() && !texto.equals("0.00");
        marcarError(campo, valido);
        return valido;
    }

    private boolean areaEsValida(javax.swing.JTextArea area) {
        return !area.getText().trim().isEmpty();
    }

    private boolean grupoChecksEsValido(javax.swing.JCheckBox... checks) {
        boolean alMenosUno = false;
        for (javax.swing.JCheckBox chk : checks) {
            if (chk.isSelected()) {
                alMenosUno = true;
                break;
            }
        }
        for (javax.swing.JCheckBox chk : checks) {
            marcarError(chk, alMenosUno);
        }
        return alMenosUno;
    }

    private boolean campoCondicionalEsValido(javax.swing.JCheckBox checkSi, javax.swing.JTextField campo) {
        if (checkSi.isSelected()) {
            return campoEsValido(campo);
        }
        return true;
    }

    /**
     * Valida que se haya seleccionado una forma de pago y que su monto no este
     * vacio.
     */
    public boolean validarCampos() {
        boolean v1 = grupoChecksEsValido(chkContadoIndividual, chkCincuentaInicial,
                chkCuatroPagosIguales, chkContadoHermanos, chkCuatroPagosHermanos);

        boolean v2 = campoCondicionalEsValido(chkContadoIndividual, txtMontoContadoIndividual);
        boolean v3 = campoCondicionalEsValido(chkCincuentaInicial, txtMontoCincuentaInicial);
        boolean v4 = campoCondicionalEsValido(chkCuatroPagosIguales, txtMontoCuatroPagosIguales);
        boolean v5 = campoCondicionalEsValido(chkContadoHermanos, txtMontoContadoHermanos);
        boolean v6 = campoCondicionalEsValido(chkCuatroPagosHermanos, txtMontoCuatroPagosHermanos);

        return v1 && v2 && v3 && v4 && v5 && v6;
    }

    /**
     * Metodos ayudante que recibe cualquier cantidad de CheckBoxes y los mete
     * en un mismo grupo para poder seleccionar uno y mas
     */
    private void crearGrupo(javax.swing.JCheckBox... casillas) {
        javax.swing.ButtonGroup grupo = new javax.swing.ButtonGroup();
        for (javax.swing.JCheckBox casilla : casillas) {
            grupo.add(casilla);
        }

    }

    private void agruparCasillas() {
        crearGrupo(chkContadoIndividual, chkCincuentaInicial, chkCuatroPagosIguales, chkContadoHermanos, chkCuatroPagosHermanos);
    }

    /**
     * Pinta el fondo de cualquier dato de color si hay error.
     */
    private void marcarError(javax.swing.JComponent componente, boolean valido) {
        if (componente instanceof javax.swing.JCheckBox) {
            componente.setOpaque(true);
            componente.setBackground(valido ? null : new java.awt.Color(255, 235, 235));
        } else {
            componente.setBackground(valido ? java.awt.Color.WHITE : new java.awt.Color(255, 235, 235));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkCincuentaInicial;
    private javax.swing.JCheckBox chkContadoHermanos;
    private javax.swing.JCheckBox chkContadoIndividual;
    private javax.swing.JCheckBox chkCuatroPagosHermanos;
    private javax.swing.JCheckBox chkCuatroPagosIguales;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNotaInformativaPago;
    private javax.swing.JLabel lblTituloTutor;
    private javax.swing.JTextField txtMontoCincuentaInicial;
    private javax.swing.JTextField txtMontoContadoHermanos;
    private javax.swing.JTextField txtMontoContadoIndividual;
    private javax.swing.JTextField txtMontoCuatroPagosHermanos;
    private javax.swing.JTextField txtMontoCuatroPagosIguales;
    // End of variables declaration//GEN-END:variables
}
